
FROM python:latest
LABEL authors="ismarhahazov"
ENV PYTHONWRITEBYTECODE 1
ENV PYTHONBUFFERED 1
WORKDIR /Meyman_Backend

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r /Meyman_Backend/requirements.txt
ADD . .