version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: DockerFile
    container_name: backend
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - backend
    volumes:
      - .:/meymanbackend
  postgres-db:
    image: 'postgres:15'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
networks:
  backend:
    driver: bridge
volumes:
  postgres-data:

