# Generated by Django 4.2.3 on 2023-08-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author_fullname',
        ),
    ]
