# Generated by Django 4.2.3 on 2023-08-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_favorite',
        ),
    ]
