# Generated by Django 4.2.3 on 2023-07-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_favorite',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Добавить в избраное'),
        ),
    ]
