# Generated by Django 4.2.3 on 2023-08-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author_fullname',
        ),
    ]
