# Generated by Django 4.2.3 on 2023-07-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_by_reviews',
            field=models.PositiveIntegerField(blank=True, choices=[(9, '9+: Замечательно'), (8, '8+: Отлично'), (7, '7+: Хорошо'), (5, '5+: Неплохо')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.PositiveIntegerField(blank=True, choices=[(1, ' ✭ '), (2, ' ✭  ✭ '), (3, ' ✭  ✭  ✭ '), (4, ' ✭  ✭  ✭  ✭ '), (5, ' ✭  ✭  ✭  ✭  ✭ ')], default=0, null=True),
        ),
    ]
