# Generated by Django 4.2.3 on 2023-07-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.PositiveIntegerField(blank=True, choices=[(1, ' ✭ '), (2, ' ✭  ✭ '), (3, ' ✭  ✭  ✭ '), (4, ' ✭  ✭  ✭  ✭ '), (5, ' ✭  ✭  ✭  ✭  ✭ ')], default=0, null=True),
        ),
    ]
