# Generated by Django 4.2.3 on 2023-07-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_stars'),
        ('review', '0002_review_rating_by_reviews_alter_review_stars'),
    ]

    operations = [
    ]
