# Generated by Django 4.2.3 on 2023-08-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_merge_20230731_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating_by_reviews',
        ),
    ]
