# Generated by Django 4.2.3 on 2023-07-22 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='city',
            new_name='location',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.FloatField(),
        ),
    ]
