# Generated by Django 4.2.3 on 2023-08-04 18:11

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_location', models.CharField(choices=[('Бишкек', 'Бишкек'), ('Джалал-Абад', 'Джалал-Абад'), ('Иссык-Куль', 'Иссык-Куль'), ('Ош', 'Ош'), ('Нарын', 'Нарын'), ('Талас', 'Талас'), ('Баткен', 'Баткен')], max_length=50, verbose_name='Область нахождения машины')),
                ('image', models.ImageField(upload_to='images/car/', verbose_name='Изображение автомобиля')),
                ('category', models.CharField(choices=[('Легковушка', 'Легковушка'), ('Минивэн', 'Минивэн'), ('Внедорожник', 'Внедорожник'), ('Автобус', 'Автобус'), ('Кроссовер', 'Кроссовер')], max_length=50, verbose_name='Категория автомобиля')),
                ('transmission', models.CharField(choices=[('Механическая', 'Механическая'), ('Автоматическая', 'Автоматическая'), ('Другое', 'Другое')], max_length=50, verbose_name='Тип коробки передач')),
                ('steering', models.CharField(choices=[('Левый', 'Левый'), ('Правый', 'Правый')], max_length=50, verbose_name='Руль')),
                ('body_type', models.CharField(choices=[('Седан', 'Седан'), ('Купе', 'Купе'), ('Хэтчбек', 'Хэтчбек'), ('Лифтбек', 'Лифтбек'), ('Фастбэк', 'Фастбэк'), ('Универсал', 'Универсал'), ('Кроссовер', 'Кроссовер'), ('Внедорожник', 'Внедорожник'), ('Легковой фургон', 'Легковой фургон'), ('Минивэн', 'Минивэн'), ('Компактвэн', 'Компактвэн'), ('Микровэн', 'Микровэн'), ('Кабриолет', 'Кабриолет'), ('Родстер', 'Родстер'), ('Тарга', 'Тарга'), ('Ландо', 'Ландо'), ('Лимузин', 'Лимузин')], max_length=50, verbose_name='Тип кузова')),
                ('drive_type', models.CharField(choices=[('Передний', 'Передний'), ('Задний', 'Задний'), ('Полный', 'Полный')], max_length=50, verbose_name='Тип привода')),
                ('fuel_type', models.CharField(choices=[('Бензин', 'Бензин'), ('Бензин/Газ', 'Бензин/Газ'), ('Газ', 'Газ'), ('Дизель', 'Дизель'), ('Электрический', 'Электрический'), ('Другое', 'Другое')], max_length=50, verbose_name='Тип топлива')),
                ('passenger', models.CharField(choices=[('2', '2 пассажира'), ('5', '5 пассажиров'), ('8', '8 пассажиров'), ('Другое', 'Другое')], max_length=50, verbose_name='Вместимость пассажиров')),
                ('condition', models.CharField(choices=[('Хорошее', 'Хорошее'), ('Идеальное', 'Идеальное'), ('Новое', 'Новое')], max_length=50, verbose_name='Состояние автомобиля')),
                ('currency', models.CharField(choices=[('KGS', 'Сом (KGS)'), ('USD', 'Доллар (USD)'), ('EUR', 'Евро (EUR)')], max_length=10, verbose_name='Валюта')),
                ('minimum_age', models.PositiveIntegerField(verbose_name='Минимальный возраст водителя')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма аренды (Сутки)')),
                ('car_address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('brand', models.CharField(choices=[('Мерседес-бенц', 'Мерседес-бенц'), ('Лендровер', 'Лендровер'), ('БМВ', 'БМВ'), ('Вольво', 'Вольво'), ('Шевролед', 'Шевролед'), ('Фольксваген', 'Фольксваген'), ('Хонда', 'Хонда'), ('Ауди', 'Ауди'), ('Хендай', 'Хендай'), ('Форд', 'Форд'), ('Киа', 'Киа'), ('Лексус', 'Лексус'), ('Мицубиси', 'Мицубиси'), ('Рено', 'Рено'), ('Опель', 'Опель'), ('Субару', 'Субару'), ('Мазда', 'Мазда'), ('Порше', 'Порше'), ('Дэу', 'Дэу'), ('Лада', 'Лада'), ('Сузуки', 'Сузуки'), ('Инфинити', 'Инфинити'), ('Ссанг Йонг', 'Ссанг Йонг'), ('Ниссан', 'Ниссан'), ('Тойота', 'Тойота')], max_length=50, verbose_name='Марка автомобиля')),
                ('color', models.CharField(blank=True, choices=[('Серебристый', 'Серебристый'), ('Черный', 'Черный'), ('Белый', 'Белый'), ('Серый', 'Серый'), ('Бежевый', 'Бежевый'), ('Бирюзовый', 'Бирюзовый'), ('Бордовый', 'Бордовый'), ('Бронза', 'Бронза'), ('Хамелеон', 'Хамелеон'), ('Жёлтый', 'Жёлтый'), ('Зеленый', 'Зеленый'), ('Золотоый', 'Золотоый'), ('Коричневый', 'Коричневый'), ('Фиолетовый', 'Фиолетовый'), ('Синий', 'Синий'), ('Красный', 'Красный'), ('Оранжевый', 'Оранжевый'), ('Розовый', 'Розовый'), ('Сиреневый', 'Сиреневый'), ('Вишьня', 'Вишьня'), ('Баклажан', 'Баклажан'), ('Голубой', 'Голубой')], max_length=50, verbose_name='Цвет автомобиля')),
                ('passenger_capacity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], default=1, verbose_name='Количество пассажирских мест')),
                ('year', models.PositiveIntegerField(choices=[(1900, '1900'), (1901, '1901'), (1902, '1902'), (1903, '1903'), (1904, '1904'), (1905, '1905'), (1906, '1906'), (1907, '1907'), (1908, '1908'), (1909, '1909'), (1910, '1910'), (1911, '1911'), (1912, '1912'), (1913, '1913'), (1914, '1914'), (1915, '1915'), (1916, '1916'), (1917, '1917'), (1918, '1918'), (1919, '1919'), (1920, '1920'), (1921, '1921'), (1922, '1922'), (1923, '1923'), (1924, '1924'), (1925, '1925'), (1926, '1926'), (1927, '1927'), (1928, '1928'), (1929, '1929'), (1930, '1930'), (1931, '1931'), (1932, '1932'), (1933, '1933'), (1934, '1934'), (1935, '1935'), (1936, '1936'), (1937, '1937'), (1938, '1938'), (1939, '1939'), (1940, '1940'), (1941, '1941'), (1942, '1942'), (1943, '1943'), (1944, '1944'), (1945, '1945'), (1946, '1946'), (1947, '1947'), (1948, '1948'), (1949, '1949'), (1950, '1950'), (1951, '1951'), (1952, '1952'), (1953, '1953'), (1954, '1954'), (1955, '1955'), (1956, '1956'), (1957, '1957'), (1958, '1958'), (1959, '1959'), (1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029')], verbose_name='Год выпуска')),
                ('description', models.TextField(blank=True, verbose_name='Описание автомобиля')),
                ('fuel_consumption', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Расход топлива на 100км')),
                ('driving_experience', models.PositiveIntegerField(verbose_name='Минимальный стаж вождения для аренды')),
                ('payment_method', models.CharField(choices=[('Pay now', 'К оплате сейчас'), ('Prepayment', 'Предоплата'), ('Cash payment', 'Оплата наличными')], max_length=20, verbose_name='Способ оплаты')),
                ('pickup_region', multiselectfield.db.fields.MultiSelectField(choices=[('Бишкек', 'Бишкек'), ('Джалал-Абад', 'Джалал-Абад'), ('Иссык-Куль', 'Иссык-Куль'), ('Ош', 'Ош'), ('Нарын', 'Нарын'), ('Талас', 'Талас'), ('Баткен', 'Баткен'), ('Все', 'Все')], max_length=100, verbose_name='Регион получения')),
                ('return_region', multiselectfield.db.fields.MultiSelectField(choices=[('Бишкек', 'Бишкек'), ('Джалал-Абад', 'Джалал-Абад'), ('Иссык-Куль', 'Иссык-Куль'), ('Ош', 'Ош'), ('Нарын', 'Нарын'), ('Талас', 'Талас'), ('Баткен', 'Баткен'), ('Все', 'Все')], max_length=100, verbose_name='Регион возврата')),
                ('has_safety_equipment', multiselectfield.db.fields.MultiSelectField(choices=[('fire_extinguisher', 'Наличие огнетушителя'), ('first_aid_kit', 'Наличие аптечки'), ('spare_wheel', 'Наличие запасного колеса'), ('airbags', 'Наличие подушка безопасности'), ('emergency_tools', 'Наличие инструментов аварийной ситуации'), ('dashboard_camera', 'Наличие авторегистратора')], max_length=100, verbose_name='Наличие системы безопасности')),
                ('amenities', multiselectfield.db.fields.MultiSelectField(choices=[('Кондиционер', 'Кондиционер'), ('Датчик парковки', 'Датчик парковки'), ('Подогрев сидений и руля', 'Подогрев сидений и руля')], max_length=100, verbose_name='Внутренние удобства')),
                ('check_in_time', models.TimeField(verbose_name='Время заезда')),
                ('check_out_time', models.TimeField(verbose_name='Время отъезда')),
                ('can_arrange_pickup_return', models.BooleanField(default=True, verbose_name='Может ли клиент договориться о месте получения/возврата автомобиля')),
            ],
            options={
                'verbose_name': 'Трансфер',
                'verbose_name_plural': 'Трансферы',
            },
        ),
        migrations.CreateModel(
            name='TransferReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_location', models.CharField(max_length=255, verbose_name='Место получения трансфера')),
                ('destination_location', models.CharField(max_length=255, verbose_name='Куда вы хотите поехать')),
                ('pickup_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 8, 4))], verbose_name='Дата получения трансфера')),
                ('pickup_time', models.TimeField(verbose_name='Время получения трансфера')),
                ('return_location', models.CharField(max_length=255, verbose_name='Место возврата трансфера')),
                ('return_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 8, 4))], verbose_name='Дата возврата трансфера')),
                ('return_time', models.TimeField(verbose_name='Время возврата трансфера')),
                ('different_pickup_places', models.BooleanField(default=False, verbose_name='Разные места получения')),
                ('with_driver', models.BooleanField(default=False, verbose_name='Трансфер с водителем')),
                ('transfer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_service.transfer', verbose_name='Трансфер')),
            ],
            options={
                'verbose_name': 'Бронь трансфера',
                'verbose_name_plural': 'Бронь Трансферов',
            },
        ),
    ]
