# Generated by Django 4.2.3 on 2023-07-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='return_location',
            field=models.CharField(max_length=255, verbose_name='Место возврата трансфера'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_location',
            field=models.CharField(max_length=255, verbose_name='Место получения трансфера'),
        ),
    ]
