# Generated by Django 4.2.3 on 2023-08-03 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferreservation',
            options={'verbose_name': 'Бронь трансфера', 'verbose_name_plural': 'Бронь Трансферов'},
        ),
        migrations.AlterField(
            model_name='transferreservation',
            name='transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_service.transfer', verbose_name=' Бронь трансфера'),
        ),
    ]
