# Generated by Django 4.2.3 on 2023-08-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='air_conditioner',
            field=models.CharField(choices=[('Нет', 'Нет'), ('Да', 'Да')], max_length=10, verbose_name='Кондиционер'),
        ),
    ]
