# Generated by Django 4.2.3 on 2023-08-07 19:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='pickup_region',
        ),
        migrations.AddField(
            model_name='transfer',
            name='operating_area',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bishkek', 'Бишкек'), ('Jalal-Abad', 'Джалал-Абад'), ('Issyk-Kul', 'Иссык-Куль'), ('Osh', 'Ош'), ('Naryn', 'Нарын'), ('Talas', 'Талас'), ('Batken', 'Баткен')], default=1, max_length=100, verbose_name='Территории эксплуатации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='pickup_location',
            field=models.CharField(choices=[('Bishkek', 'Бишкек'), ('Jalal-Abad', 'Джалал-Абад'), ('Issyk-Kul', 'Иссык-Куль'), ('Osh', 'Ош'), ('Naryn', 'Нарын'), ('Talas', 'Талас'), ('Batken', 'Баткен')], default=1, max_length=100, verbose_name='Место получения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='return_location',
            field=models.CharField(choices=[('Bishkek', 'Бишкек'), ('Jalal-Abad', 'Джалал-Абад'), ('Issyk-Kul', 'Иссык-Куль'), ('Osh', 'Ош'), ('Naryn', 'Нарын'), ('Talas', 'Талас'), ('Batken', 'Баткен')], default=1, max_length=100, verbose_name='Место возврата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='car_address',
            field=models.CharField(max_length=255, verbose_name='Адрес получения'),
        ),
    ]
