field = models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 7, 27))],
                         verbose_name='Заезд'),
field = models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 7, 27))],
                         verbose_name='Выезд'),
field = models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 7, 27))],
                         verbose_name='Дата получения трансфера'),
field = models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 7, 27))],
                         verbose_name='Дата возврата трансфера'),
