# Generated by Django 4.2.3 on 2023-07-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='destination_location',
            field=models.CharField(default=1, max_length=255, verbose_name='Куда вы хотите поехать'),
            preserve_default=False,
        ),
    ]
