# Generated by Django 4.2.3 on 2023-08-02 21:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0002_alter_car_air_conditioner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='air_conditioner',
        ),
        migrations.AddField(
            model_name='car',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Кондиционер', 'Кондиционер'), ('Датчик парковки', 'Датчик парковки'), ('Подогрев сидений и руля', 'Подогрев сидений и руля')], default=1, max_length=100, verbose_name='Внутренние удобства'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='pickup_region',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Бишкек', 'Бишкек'), ('Джалал-Абад', 'Джалал-Абад'), ('Иссык-Куль', 'Иссык-Куль'), ('Ош', 'Ош'), ('Нарын', 'Нарын'), ('Талас', 'Талас'), ('Баткен', 'Баткен'), ('Все', 'Все')], max_length=100, verbose_name='Регион получения'),
        ),
        migrations.AlterField(
            model_name='car',
            name='return_region',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Бишкек', 'Бишкек'), ('Джалал-Абад', 'Джалал-Абад'), ('Иссык-Куль', 'Иссык-Куль'), ('Ош', 'Ош'), ('Нарын', 'Нарын'), ('Талас', 'Талас'), ('Баткен', 'Баткен'), ('Все', 'Все')], max_length=100, verbose_name='Регион возврата'),
        ),
    ]
