# Generated by Django 4.2.3 on 2023-08-03 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0002_alter_transferreservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferreservation',
            name='transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_service.transfer', verbose_name='Трансфер'),
        ),
    ]
