# Generated by Django 4.2.3 on 2023-08-06 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferreservation',
            name='transfer',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='travel_service.transfer', verbose_name='Трансфер'),
            preserve_default=False,
        ),
    ]
