# Generated by Django 4.2.3 on 2023-08-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0002_remove_transfer_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferimage',
            name='image',
            field=models.ImageField(default=1, upload_to='images/car/', verbose_name='Изображение автомобиля'),
            preserve_default=False,
        ),
    ]
