# Generated by Django 4.2.3 on 2023-08-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='car_location',
            new_name='location',
        ),
    ]
