# Generated by Django 4.2.3 on 2023-08-04 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0003_rename_car_location_transfer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='image',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='color',
            field=models.CharField(choices=[('Серебристый', 'Серебристый'), ('Черный', 'Черный'), ('Белый', 'Белый'), ('Серый', 'Серый'), ('Бежевый', 'Бежевый'), ('Бирюзовый', 'Бирюзовый'), ('Бордовый', 'Бордовый'), ('Бронза', 'Бронза'), ('Хамелеон', 'Хамелеон'), ('Жёлтый', 'Жёлтый'), ('Зеленый', 'Зеленый'), ('Золотоый', 'Золотоый'), ('Коричневый', 'Коричневый'), ('Фиолетовый', 'Фиолетовый'), ('Синий', 'Синий'), ('Красный', 'Красный'), ('Оранжевый', 'Оранжевый'), ('Розовый', 'Розовый'), ('Сиреневый', 'Сиреневый'), ('Вишьня', 'Вишьня'), ('Баклажан', 'Баклажан'), ('Голубой', 'Голубой')], max_length=50, verbose_name='Цвет автомобиля'),
        ),
        migrations.CreateModel(
            name='TransferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/car/', verbose_name='Изображение автомобиля')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_images', to='travel_service.transfer')),
            ],
            options={
                'verbose_name': 'Изображение трансфера',
                'verbose_name_plural': 'Изображения тарнсферов',
            },
        ),
    ]
