# Generated by Django 4.2.3 on 2023-08-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0003_transferreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferreview',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_service.transfer', verbose_name='Название трансфера'),
        ),
    ]
