# Generated by Django 4.2.3 on 2023-08-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0003_alter_transferreservation_transfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'verbose_name': 'Трансфер', 'verbose_name_plural': 'Трансферы'},
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='model',
        ),
    ]
