# Generated by Django 4.2.3 on 2023-08-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0003_alter_transfer_operating_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='driver_service',
            field=models.BooleanField(default=False, verbose_name='Услуга водителя'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='can_arrange_pickup_return',
            field=models.BooleanField(default=True, verbose_name='Договор о месте получения/возврата автомобиля'),
        ),
    ]
