# Generated by Django 4.2.3 on 2023-08-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0003_alter_transferreservation_pickup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferreview',
            name='cleanliness_level',
            field=models.CharField(choices=[(10, 'Замечательно'), (9, 'Превосходно'), (8, 'Очень хорошо'), (7, 'Хорошо'), (6, 'Достаточно хорошо'), (5, 'Нормально'), (4, 'Неудовлетворительно'), (3, 'Плохо'), (2, 'Очень плохо'), (1, 'Ужасно')], default=1, max_length=2, verbose_name='Уровень чистоты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferreview',
            name='comfortable_driving',
            field=models.CharField(choices=[(10, 'Замечательно'), (9, 'Превосходно'), (8, 'Очень хорошо'), (7, 'Хорошо'), (6, 'Достаточно хорошо'), (5, 'Нормально'), (4, 'Неудовлетворительно'), (3, 'Плохо'), (2, 'Очень плохо'), (1, 'Ужасно')], default=1, max_length=2, verbose_name='Комфорт вождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferreview',
            name='how_it_went',
            field=models.CharField(choices=[(10, 'Замечательно'), (9, 'Превосходно'), (8, 'Очень хорошо'), (7, 'Хорошо'), (6, 'Достаточно хорошо'), (5, 'Нормально'), (4, 'Неудовлетворительно'), (3, 'Плохо'), (2, 'Очень плохо'), (1, 'Ужасно')], default=1, max_length=2, verbose_name='Как все прошло'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferreview',
            name='price_quality_ratio',
            field=models.CharField(choices=[(10, 'Замечательно'), (9, 'Превосходно'), (8, 'Очень хорошо'), (7, 'Хорошо'), (6, 'Достаточно хорошо'), (5, 'Нормально'), (4, 'Неудовлетворительно'), (3, 'Плохо'), (2, 'Очень плохо'), (1, 'Ужасно')], default=1, max_length=2, verbose_name='Соотношение цены и качества'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferreview',
            name='safety_level',
            field=models.CharField(choices=[(10, 'Замечательно'), (9, 'Превосходно'), (8, 'Очень хорошо'), (7, 'Хорошо'), (6, 'Достаточно хорошо'), (5, 'Нормально'), (4, 'Неудовлетворительно'), (3, 'Плохо'), (2, 'Очень плохо'), (1, 'Ужасно')], default=1, max_length=2, verbose_name='Уровень безопасности'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferreview',
            name='technical_condition',
            field=models.CharField(choices=[(10, 'Замечательно'), (9, 'Превосходно'), (8, 'Очень хорошо'), (7, 'Хорошо'), (6, 'Достаточно хорошо'), (5, 'Нормально'), (4, 'Неудовлетворительно'), (3, 'Плохо'), (2, 'Очень плохо'), (1, 'Ужасно')], default=1, max_length=2, verbose_name='Техническое состояние'),
            preserve_default=False,
        ),
    ]
