# Generated by Django 4.2.3 on 2023-08-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0004_car_alter_search_check_in_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='driving_experience',
        ),
    ]
