# Generated by Django 4.2.3 on 2023-08-04 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0004_remove_transfer_image_alter_transfer_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2025)], verbose_name='Год выпуска'),
        ),
    ]
