# Generated by Django 4.2.3 on 2023-08-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0004_transfer_driver_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='car_address',
        ),
    ]
