# Generated by Django 4.2.3 on 2023-08-10 15:37

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0004_alter_transferreview_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Кондиционер', 'Кондиционер'), ('Датчик парковки', 'Датчик парковки'), ('Подогрев сидений и руля', 'Подогрев сидений и руля'), ('Детское кресло', 'Детское кресло')], max_length=100, verbose_name='Внутренние удобства'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='body_type',
            field=models.CharField(choices=[('Седан', 'Седан'), ('Купе', 'Купе'), ('Хэтчбек', 'Хэтчбек'), ('Лифтбек', 'Лифтбек'), ('Фастбэк', 'Фастбэк'), ('Универсал', 'Универсал'), ('Кроссовер', 'Кроссовер'), ('Внедорожник', 'Внедорожник'), ('Легковой фургон', 'Легковой фургон'), ('Минивэн', 'Минивэн'), ('Компактвэн', 'Компактвэн'), ('Микровэн', 'Микровэн'), ('Кабриолет', 'Кабриолет'), ('Родстер', 'Родстер'), ('Тарга', 'Тарга'), ('Ландо', 'Ландо'), ('Лимузин', 'Лимузин')], max_length=50, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='brand',
            field=models.CharField(choices=[('Мерседес-бенц', 'Мерседес-бенц'), ('Лендровер', 'Лендровер'), ('БМВ', 'БМВ'), ('Вольво', 'Вольво'), ('Шевролед', 'Шевролед'), ('Фольксваген', 'Фольксваген'), ('Хонда', 'Хонда'), ('Ауди', 'Ауди'), ('Хендай', 'Хендай'), ('Форд', 'Форд'), ('Киа', 'Киа'), ('Лексус', 'Лексус'), ('Мицубиси', 'Мицубиси'), ('Рено', 'Рено'), ('Опель', 'Опель'), ('Субару', 'Субару'), ('Мазда', 'Мазда'), ('Порше', 'Порше'), ('Дэу', 'Дэу'), ('Лада', 'Лада'), ('Сузуки', 'Сузуки'), ('Инфинити', 'Инфинити'), ('Ссанг Йонг', 'Ссанг Йонг'), ('Ниссан', 'Ниссан'), ('Тойота', 'Тойота')], max_length=50, verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='category',
            field=models.CharField(choices=[('Легковушка', 'Легковушка'), ('Минивэн', 'Минивэн'), ('Внедорожник', 'Внедорожник'), ('Автобус', 'Автобус'), ('Кроссовер', 'Кроссовер')], max_length=50, verbose_name='Категория автомобиля'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='color',
            field=models.CharField(choices=[('Серебристый', 'Серебристый'), ('Черный', 'Черный'), ('Белый', 'Белый'), ('Серый', 'Серый'), ('Бежевый', 'Бежевый'), ('Бирюзовый', 'Бирюзовый'), ('Бордовый', 'Бордовый'), ('Бронза', 'Бронза'), ('Хамелеон', 'Хамелеон'), ('Жёлтый', 'Жёлтый'), ('Зеленый', 'Зеленый'), ('Золотой', 'Золотой'), ('Коричневый', 'Коричневый'), ('Фиолетовый', 'Фиолетовый'), ('Синий', 'Синий'), ('Красный', 'Красный'), ('Оранжевый', 'Оранжевый'), ('Розовый', 'Розовый'), ('Сиреневый', 'Сиреневый'), ('Вишня', 'Вишня'), ('Баклажан', 'Баклажан'), ('Голубой', 'Голубой')], max_length=50, verbose_name='Цвет автомобиля'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='condition',
            field=models.CharField(choices=[('Хорошее', 'Хорошее'), ('Идеальное', 'Идеальное'), ('Новое', 'Новое')], max_length=50, verbose_name='Состояние автомобиля'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='currency',
            field=models.CharField(choices=[('Сом (KGS)', 'Сом (KGS)'), ('Доллар (USD)', 'Доллар (USD)'), ('Евро (EUR)', 'Евро (EUR)')], max_length=25, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='drive_type',
            field=models.CharField(choices=[('Передний', 'Передний'), ('Задний', 'Задний'), ('Полный', 'Полный')], max_length=50, verbose_name='Тип привода'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='fuel_type',
            field=models.CharField(choices=[('Бензин', 'Бензин'), ('Бензин/Газ', 'Бензин/Газ'), ('Газ', 'Газ'), ('Дизель', 'Дизель'), ('Электрический', 'Электрический'), ('Другое', 'Другое')], max_length=50, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='operating_area',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Бишкек', 'Бишкек'), ('Джалал-Абад', 'Джалал-Абад'), ('Иссык-Куль', 'Иссык-Куль'), ('Ош', 'Ош'), ('Нарын', 'Нарын'), ('Талас', 'Талас'), ('Баткен', 'Баткен'), ('По всему КР', 'По всему КР')], max_length=100, verbose_name='Территории эксплуатации'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='passenger',
            field=models.CharField(choices=[('2 passengers', '2 пассажира'), ('5 passengers', '5 пассажиров'), ('8 passengers', '8 пассажиров'), ('Другое', 'Другое')], max_length=50, verbose_name='Вместимость пассажиров'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='payment_method',
            field=models.CharField(choices=[('К оплате сейчас', 'К оплате сейчас'), ('Предоплата', 'Предоплата'), ('Оплата наличными', 'Оплата наличными')], max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='pickup_location',
            field=models.CharField(choices=[('Бишкек', 'Бишкек'), ('Джалал-Абад', 'Джалал-Абад'), ('Иссык-Куль', 'Иссык-Куль'), ('Ош', 'Ош'), ('Нарын', 'Нарын'), ('Талас', 'Талас'), ('Баткен', 'Баткен')], max_length=100, verbose_name='Место получения'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='return_location',
            field=models.CharField(choices=[('Бишкек', 'Бишкек'), ('Джалал-Абад', 'Джалал-Абад'), ('Иссык-Куль', 'Иссык-Куль'), ('Ош', 'Ош'), ('Нарын', 'Нарын'), ('Талас', 'Талас'), ('Баткен', 'Баткен')], max_length=100, verbose_name='Место возврата'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='safety_equipment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Наличие огнетушителя', 'Наличие огнетушителя'), ('Наличие аптечки', 'Наличие аптечки'), ('Наличие запасного колеса', 'Наличие запасного колеса'), ('Наличие подушка безопасности', 'Наличие подушка безопасности'), ('Наличие инструментов аварийной ситуации', 'Наличие инструментов аварийной ситуации'), ('Наличие авторегистратора', 'Наличие авторегистратора')], max_length=100, verbose_name='Наличие системы безопасности'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='steering',
            field=models.CharField(choices=[('Левый', 'Левый'), ('Правый', 'Правый')], max_length=50, verbose_name='Руль'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transmission',
            field=models.CharField(choices=[('Механическая', 'Механическая'), ('Автоматическая', 'Автоматическая'), ('Другое', 'Другое')], max_length=50, verbose_name='Тип коробки передач'),
        ),
    ]
