# Generated by Django 4.2.3 on 2023-08-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0005_remove_car_driving_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='driving_experience',
            field=models.PositiveIntegerField(default=1, verbose_name='Минимальный стаж вождения для аренды'),
            preserve_default=False,
        ),
    ]
