# Generated by Django 4.2.3 on 2023-08-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0005_transferreservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='year',
            field=models.PositiveIntegerField(max_length=4, verbose_name='Год выпуска автомобиля'),
        ),
    ]
