# Generated by Django 4.2.3 on 2023-08-10 18:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0005_alter_transfer_amenities_alter_transfer_body_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Кондиционер', 'Кондиционер'), ('Датчик парковки', 'Датчик парковки'), ('Подогрев сидений и руля', 'Подогрев сидений и руля'), ('Детское кресло', 'Детское кресло')], max_length=150, verbose_name='Внутренние удобства'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='safety_equipment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Наличие огнетушителя', 'Наличие огнетушителя'), ('Наличие аптечки', 'Наличие аптечки'), ('Наличие запасного колеса', 'Наличие запасного колеса'), ('Наличие подушка безопасности', 'Наличие подушка безопасности'), ('Наличие инструментов аварийной ситуации', 'Наличие инструментов аварийной ситуации'), ('Наличие авторегистратора', 'Наличие авторегистратора')], max_length=255, verbose_name='Наличие системы безопасности'),
        ),
    ]
