# Generated by Django 4.2.3 on 2023-08-05 08:31

import datetime
import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0005_alter_transfer_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Air conditioning', 'Кондиционер'), ('Parking sensor', 'Датчик парковки'), ('Heated seats and steering wheel', 'Подогрев сидений и руля'), ('Child seat', 'Детское кресло')], max_length=100, verbose_name='Внутренние удобства'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='body_type',
            field=models.CharField(choices=[('Sedan', 'Седан'), ('Coupe', 'Купе'), ('Hatchback', 'Хэтчбек'), ('Liftback', 'Лифтбек'), ('Fastback', 'Фастбэк'), ('Wagon', 'Универсал'), ('Crossover', 'Кроссовер'), ('SUV', 'Внедорожник'), ('Passenger van', 'Легковой фургон'), ('Minivan', 'Минивэн'), ('Compact van', 'Компактвэн'), ('Microvan', 'Микровэн'), ('Convertible', 'Кабриолет'), ('Roadster', 'Родстер'), ('Targa', 'Тарга'), ('Landaulet', 'Ландо'), ('Limousine', 'Лимузин')], max_length=50, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='brand',
            field=models.CharField(choices=[('Mercedes-Benz', 'Мерседес-бенц'), ('Land Rover', 'Лендровер'), ('BMW', 'БМВ'), ('Volvo', 'Вольво'), ('Chevrolet', 'Шевролед'), ('Volkswagen', 'Фольксваген'), ('Honda', 'Хонда'), ('Audi', 'Ауди'), ('Hyundai', 'Хендай'), ('Ford', 'Форд'), ('Kia', 'Киа'), ('Lexus', 'Лексус'), ('Mitsubishi', 'Мицубиси'), ('Renault', 'Рено'), ('Opel', 'Опель'), ('Subaru', 'Субару'), ('Mazda', 'Мазда'), ('Porsche', 'Порше'), ('Daewoo', 'Дэу'), ('Lada', 'Лада'), ('Suzuki', 'Сузуки'), ('Infiniti', 'Инфинити'), ('SsangYong', 'Ссанг Йонг'), ('Nissan', 'Ниссан'), ('Toyota', 'Тойота')], max_length=50, verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='category',
            field=models.CharField(choices=[('Car', 'Легковушка'), ('Minivan', 'Минивэн'), ('SUV', 'Внедорожник'), ('Bus', 'Автобус'), ('Crossover', 'Кроссовер')], max_length=50, verbose_name='Категория автомобиля'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='color',
            field=models.CharField(choices=[('Silver', 'Серебристый'), ('Black', 'Черный'), ('White', 'Белый'), ('Gray', 'Серый'), ('Beige', 'Бежевый'), ('Turquoise', 'Бирюзовый'), ('Burgundy', 'Бордовый'), ('Bronze', 'Бронза'), ('Chameleon', 'Хамелеон'), ('Yellow', 'Жёлтый'), ('Green', 'Зеленый'), ('Gold', 'Золотоый'), ('Brown', 'Коричневый'), ('Purple', 'Фиолетовый'), ('Blue', 'Синий'), ('Red', 'Красный'), ('Orange', 'Оранжевый'), ('Pink', 'Розовый'), ('Lilac', 'Сиреневый'), ('Cherry', 'Вишьня'), ('Eggplant', 'Баклажан'), ('Light blue', 'Голубой')], max_length=50, verbose_name='Цвет автомобиля'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='condition',
            field=models.CharField(choices=[('Good', 'Хорошее'), ('Excellent', 'Идеальное'), ('New', 'Новое')], max_length=50, verbose_name='Состояние автомобиля'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='drive_type',
            field=models.CharField(choices=[('Front', 'Передний'), ('Rear', 'Задний'), ('All-wheel', 'Полный')], max_length=50, verbose_name='Тип привода'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='fuel_type',
            field=models.CharField(choices=[('Gasoline', 'Бензин'), ('Gasoline/Gas', 'Бензин/Газ'), ('Gas', 'Газ'), ('Diesel', 'Дизель'), ('Electric', 'Электрический'), ('Other', 'Другое')], max_length=50, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='location',
            field=models.CharField(choices=[('Bishkek', 'Бишкек'), ('Jalal-Abad', 'Джалал-Абад'), ('Issyk-Kul', 'Иссык-Куль'), ('Osh', 'Ош'), ('Naryn', 'Нарын'), ('Talas', 'Талас'), ('Batken', 'Баткен')], max_length=50, verbose_name='Область нахождения машины'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='passenger',
            field=models.CharField(choices=[('2', '2 passengers'), ('5', '5 passengers'), ('8', '8 passengers'), ('Other', 'Other')], max_length=50, verbose_name='Вместимость пассажиров'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='pickup_region',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bishkek', 'Бишкек'), ('Jalal-Abad', 'Джалал-Абад'), ('Issyk-Kul', 'Иссык-Куль'), ('Osh', 'Ош'), ('Naryn', 'Нарын'), ('Talas', 'Талас'), ('Batken', 'Баткен'), ('Все', 'Все')], max_length=100, verbose_name='Регион получения'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='return_region',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bishkek', 'Бишкек'), ('Jalal-Abad', 'Джалал-Абад'), ('Issyk-Kul', 'Иссык-Куль'), ('Osh', 'Ош'), ('Naryn', 'Нарын'), ('Talas', 'Талас'), ('Batken', 'Баткен'), ('Все', 'Все')], max_length=100, verbose_name='Регион возврата'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='steering',
            field=models.CharField(choices=[('Left', 'Левый'), ('Right', 'Правый')], max_length=50, verbose_name='Руль'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Механическая'), ('Automatic', 'Автоматическая'), ('Other', 'Другое')], max_length=50, verbose_name='Тип коробки передач'),
        ),
        migrations.AlterField(
            model_name='transferreservation',
            name='pickup_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 8, 5))], verbose_name='Дата получения трансфера'),
        ),
        migrations.AlterField(
            model_name='transferreservation',
            name='return_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 8, 5))], verbose_name='Дата возврата трансфера'),
        ),
    ]
