# Generated by Django 4.2.3 on 2023-08-07 21:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0005_alter_transfer_operating_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='operating_area',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bishkek', 'Бишкек'), ('Jalal-Abad', 'Джалал-Абад'), ('Issyk-Kul', 'Иссык-Куль'), ('Osh', 'Ош'), ('Naryn', 'Нарын'), ('Talas', 'Талас'), ('Batken', 'Баткен'), ('По всему КР', 'По всему КР')], max_length=100, verbose_name='Территории эксплуатации'),
        ),
    ]
