# Generated by Django 4.2.3 on 2023-08-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0006_alter_transfer_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='transfer_image',
            field=models.ImageField(upload_to='transfer', verbose_name='Изображение автомобиля'),
        ),
    ]
