# Generated by Django 4.2.3 on 2023-08-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0006_alter_transfer_amenities_alter_transfer_body_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/car/', verbose_name='Изображение автомобиля'),
        ),
    ]
