# Generated by Django 4.2.3 on 2023-08-01 13:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0006_car_driving_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='has_airbags',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_dashboard_camera',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_emergency_tools',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_fire_extinguisher',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_first_aid_kit',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_spare_wheel',
        ),
        migrations.AddField(
            model_name='car',
            name='has_safety_equipment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('fire_extinguisher', 'Огнетушитель'), ('first_aid_kit', 'Аптечка'), ('spare_wheel', 'Запасное колесо'), ('airbags', 'Подушка безопасности'), ('emergency_tools', 'Инструменты аварийной ситуации'), ('dashboard_camera', 'Авторегистратор')], default=1, max_length=100, verbose_name='Наличие системы безопасности'),
            preserve_default=False,
        ),
    ]
