# Generated by Django 4.2.3 on 2023-08-10 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0008_roomimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomImage',
            new_name='TransferImage',
        ),
    ]
