# Generated by Django 4.2.3 on 2023-08-03 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0008_alter_transfer_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)], verbose_name='Год выпуска автомобиля'),
        ),
    ]
