# Generated by Django 4.2.3 on 2023-08-01 19:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0008_car_has_airbags_car_has_dashboard_camera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='has_airbags',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_dashboard_camera',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_emergency_tools',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_fire_extinguisher',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_first_aid_kit',
        ),
        migrations.RemoveField(
            model_name='car',
            name='has_spare_wheel',
        ),
        migrations.AlterField(
            model_name='car',
            name='has_safety_equipment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('fire_extinguisher', 'Наличие огнетушителя'), ('first_aid_kit', 'Наличие аптечки'), ('spare_wheel', 'Наличие запасного колеса'), ('airbags', 'Наличие подушка безопасности'), ('emergency_tools', 'Наличие инструментов аварийной ситуации'), ('dashboard_camera', 'Наличие авторегистратора')], max_length=100, verbose_name='Наличие системы безопасности'),
        ),
    ]
