# Generated by Django 4.2.3 on 2023-08-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0008_transfer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='has_safety_equipment',
            new_name='safety_equipment',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='return_region',
        ),
    ]
