# Generated by Django 4.2.3 on 2023-08-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0010_remove_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=1, upload_to='images/car/', verbose_name='Изображение автомобиля'),
            preserve_default=False,
        ),
    ]
