# Generated by Django 4.2.3 on 2023-08-05 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0010_remove_transferreservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='image',
        ),
    ]
