# Generated by Django 4.2.3 on 2023-08-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_service', '0010_alter_transferimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferimage',
            name='transfer_image',
            field=models.ImageField(upload_to='transfers', verbose_name='Изображения Трансфера'),
        ),
    ]
