# Generated by Django 4.2.3 on 2023-07-17 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_travelservice_price_alter_travelservice_service_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travelservice')),
            ],
        ),
    ]
