# Generated by Django 4.2.3 on 2023-07-29 06:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_remove_user_avatar_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationreservation',
            name='check_in_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 7, 29))], verbose_name='Заезд'),
        ),
        migrations.AlterField(
            model_name='accommodationreservation',
            name='check_out_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 7, 29))], verbose_name='Выезд'),
        ),
        migrations.AlterField(
            model_name='carreservation',
            name='check_in_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 7, 29))], verbose_name='дата бронирование'),
        ),
        migrations.AlterField(
            model_name='carreservation',
            name='check_out_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 7, 29))]),
        ),
    ]
