# Generated by Django 4.2.3 on 2023-07-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accommodationreservation_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationreservation',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='carreservation',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_staff',
        ),
    ]
