# Generated by Django 4.2.3 on 2023-07-22 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_housing_is_favorite'),
        ('users', '0003_alter_profile_email_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='choise',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='house',
            field=models.ForeignKey(choices=[('Отели', 'Отели'), ('Хостелы', 'Хостелы'), ('Апартаменты', 'Апартаменты'), ('Гостевые дома', 'Гостевые дома'), ('Санатории', 'Санатории')], on_delete=django.db.models.deletion.CASCADE, to='travel.housing'),
        ),
    ]
