# Generated by Django 4.2.3 on 2023-07-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_accommodationreservation_check_in_date_and_more'),
        ('users', '0003_customuser_is_staff'),
    ]

    operations = [
    ]
