# Generated by Django 4.2.3 on 2023-09-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_avatar_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsite',
            old_name='user',
            new_name='profile',
        ),
    ]
