# Generated by Django 4.2.3 on 2023-09-04 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_reviewsite_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsite',
            old_name='profile',
            new_name='user',
        ),
    ]
