# Generated by Django 4.2.3 on 2023-08-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='username',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default=2, max_length=45),
            preserve_default=False,
        ),
    ]
