# Generated by Django 4.2.3 on 2023-07-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_accommodationreservation_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationreservation',
            name='payment_type',
            field=models.CharField(choices=[('К оплате сейчас', 'К оплате сейчас'), ('Предоплата', 'Предоплата'), ('Оплата наличными', 'Оплата наличными')], default='К оплате сейчас', max_length=50, verbose_name='Оплата'),
        ),
    ]
