# Generated by Django 4.2.3 on 2023-07-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_accommodationreservation_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationreservation',
            name='booking_type',
            field=models.CharField(choices=[('Без банковской карты', 'Без банковской карты'), ('Бесплатная отмена', 'Бесплатная отмена')], default='Без банковской карты', max_length=50, verbose_name='Бронирование'),
        ),
    ]
