# Generated by Django 4.2.3 on 2023-08-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='firstname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastname',
        ),
    ]
