# Generated by Django 4.2.3 on 2023-09-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertising',
            name='slug',
        ),
    ]
