# Generated by Django 4.2.3 on 2023-08-23 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0001_initial'),
        ('travel_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Альбом желаний',
                'verbose_name_plural': 'Альбомы желаний',
            },
        ),
        migrations.CreateModel(
            name='HouseFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.housing')),
                ('news', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('transfer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_service.transfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlist_album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='favorite.wishlistalbum')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
    ]
