# Generated by Django 4.2.3 on 2023-08-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('travel_service', '0002_initial'),
        ('travel', '0006_remove_wishlistalbum_user_delete_housefavorite_and_more'),
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housefavorite',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='housefavorite',
            name='object_id',
        ),
        migrations.AddField(
            model_name='housefavorite',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='TransferFavorite',
            fields=[
                ('housefavorite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='favorite.housefavorite')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_service.transfer')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('favorite.housefavorite',),
        ),
        migrations.CreateModel(
            name='HousingFavorite',
            fields=[
                ('housefavorite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='favorite.housefavorite')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.housing')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('favorite.housefavorite',),
        ),
    ]
