# Generated by Django 4.2.3 on 2023-08-30 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housefavorite',
            name='news',
        ),
        migrations.AddField(
            model_name='wishlistalbum',
            name='favorite',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='favorite.housefavorite'),
            preserve_default=False,
        ),
    ]
