# Generated by Django 4.2.3 on 2023-08-09 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('favorite', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housefavorite',
            name='news',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
    ]
