# Generated by Django 4.2.3 on 2023-08-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_remove_housefavorite_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferfavorite',
            name='housefavorite_ptr',
        ),
        migrations.RemoveField(
            model_name='transferfavorite',
            name='item',
        ),
        migrations.RemoveField(
            model_name='housefavorite',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='housefavorite',
            name='item_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housefavorite',
            name='item_type',
            field=models.CharField(choices=[('housing', 'Housing'), ('transfer', 'Transfer')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HousingFavorite',
        ),
        migrations.DeleteModel(
            name='TransferFavorite',
        ),
    ]
