# Generated by Django 4.2.3 on 2023-08-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0003_remove_housefavorite_news_wishlistalbum_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistalbum',
            name='favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='favorite.housefavorite'),
        ),
    ]
