# Generated by Django 4.2.3 on 2023-08-08 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('favorite', '0003_remove_transferfavorite_housefavorite_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housefavorite',
            old_name='item_id',
            new_name='object_id',
        ),
        migrations.RemoveField(
            model_name='housefavorite',
            name='item_type',
        ),
        migrations.AddField(
            model_name='housefavorite',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
