# Generated by Django 4.2.3 on 2023-08-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_remove_wishlistalbum_user_delete_housefavorite_and_more'),
        ('travel_service', '0002_initial'),
        ('favorite', '0004_rename_item_id_housefavorite_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housefavorite',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='housefavorite',
            name='object_id',
        ),
        migrations.AddField(
            model_name='housefavorite',
            name='housing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.housing'),
        ),
        migrations.AddField(
            model_name='housefavorite',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_service.transfer'),
        ),
    ]
