# Generated by Django 4.2.3 on 2023-08-31 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_housingreservation_check_in_date_and_more'),
        ('favorite', '0004_alter_wishlistalbum_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housefavorite',
            name='transfer',
        ),
        migrations.AlterField(
            model_name='housefavorite',
            name='housing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.housing'),
        ),
    ]
