# Generated by Django 4.2.3 on 2023-08-31 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0005_remove_housefavorite_transfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housefavorite',
            name='wishlist_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='favorite.wishlistalbum'),
        ),
    ]
