# Generated by Django 4.2.3 on 2023-08-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_remove_wishlistalbum_user_delete_housefavorite_and_more'),
        ('travel_service', '0002_initial'),
        ('favorite', '0005_remove_housefavorite_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housefavorite',
            name='housing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.housing'),
        ),
        migrations.AlterField(
            model_name='housefavorite',
            name='transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_service.transfer'),
        ),
    ]
