# Generated by Django 4.2.3 on 2023-08-31 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_housingreservation_check_in_date_and_more'),
        ('favorite', '0006_alter_housefavorite_wishlist_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housefavorite',
            name='housing',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='travel.housing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housefavorite',
            name='wishlist_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='список', to='favorite.wishlistalbum'),
        ),
        migrations.AlterField(
            model_name='wishlistalbum',
            name='favorite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='favorite.housefavorite'),
            preserve_default=False,
        ),
    ]
