# Generated by Django 4.2.3 on 2023-08-31 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0008_alter_wishlistalbum_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistalbum',
            name='favorite',
        ),
    ]
