# Generated by Django 4.2.3 on 2023-08-31 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0010_alter_housefavorite_wishlist_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housefavorite',
            name='user',
        ),
    ]
