# Generated by Django 4.2.3 on 2023-08-31 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_housingreservation_check_in_date_and_more'),
        ('favorite', '0011_remove_housefavorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housefavorite',
            name='housing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing', to='travel.housing'),
        ),
    ]
