# Generated by Django 4.2.3 on 2023-07-19 12:56

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_type', models.CharField(choices=[('Жилье целиком', 'Жилье целиком'), ('Комната', 'Комната'), ('Общая комната', 'Общая комната')], max_length=255, verbose_name='Тип размещения')),
            ],
            options={
                'verbose_name': 'Тип размещения',
                'verbose_name_plural': 'Типы размещения',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(choices=[('Односпальная', 'Односпальная'), ('Двуспальная', 'Двуспальная')], max_length=255, verbose_name='Тип кроватей')),
            ],
            options={
                'verbose_name': 'Тип кроватей',
                'verbose_name_plural': 'Типы кроватей',
            },
        ),
        migrations.CreateModel(
            name='HousingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.CharField(choices=[('Отели', 'Отели'), ('Хостелы', 'Хостелы'), ('Апартаменты', 'Апартаменты'), ('Гостиницы', 'Гостиницы')], max_length=50, verbose_name='Тип жилья')),
            ],
            options={
                'verbose_name': 'Тип жилья',
                'verbose_name_plural': 'Типы жилья',
            },
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.PositiveIntegerField(default=10, verbose_name='Минимум')),
                ('max_price', models.PositiveIntegerField(default=500, verbose_name='Максимум')),
            ],
            options={
                'verbose_name': 'Ценовой диапазон',
                'verbose_name_plural': 'Ценовые диапазоны',
            },
        ),
        migrations.CreateModel(
            name='TravelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='Название сервиса')),
                ('image', models.ImageField(upload_to='images/travel/', verbose_name='Изображение туристического сервиса')),
                ('description', models.TextField(verbose_name='Описание сервиса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('start_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 7, 19))], verbose_name='Дата начала')),
                ('end_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 7, 19))], verbose_name='Дата окончания')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступность')),
            ],
            options={
                'verbose_name': 'Туристический сервис',
                'verbose_name_plural': 'Туристические сервисы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/news', verbose_name='Картинка новости')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на источник')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='travel.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_name', models.CharField(max_length=255, verbose_name='Название места жительства')),
                ('image', models.ImageField(upload_to='images/housing/', verbose_name='Изображение места жительства')),
                ('description', models.TextField(verbose_name='Описание места жительства')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за сутки')),
                ('available_rooms', models.PositiveIntegerField(verbose_name='Количество доступных комнат')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('accommodation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.accommodationtype', verbose_name='Тип размещения')),
                ('bed_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.bedtype', verbose_name='Тип кроватей')),
                ('housing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.housingtype', verbose_name='Тип жилья')),
                ('price_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.pricerange', verbose_name='Ценовой диапазон')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_name', models.CharField(max_length=255, verbose_name='Название места жительства')),
                ('image', models.ImageField(upload_to='images/housing/', verbose_name='Изображение места жительства')),
                ('description', models.TextField(verbose_name='Описание места жительства')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за сутки')),
                ('available_rooms', models.PositiveIntegerField(verbose_name='Количество доступных комнат')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('accommodation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.accommodationtype', verbose_name='Тип размещения')),
                ('bed_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.bedtype', verbose_name='Тип кроватей')),
                ('housing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.housingtype', verbose_name='Тип жилья')),
                ('price_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.pricerange', verbose_name='Ценовой диапазон')),
            ],
            options={
                'verbose_name': 'Хостел',
                'verbose_name_plural': 'Хостелы',
            },
        ),
        migrations.CreateModel(
            name='GuestHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_name', models.CharField(max_length=255, verbose_name='Название места жительства')),
                ('image', models.ImageField(upload_to='images/housing/', verbose_name='Изображение места жительства')),
                ('description', models.TextField(verbose_name='Описание места жительства')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за сутки')),
                ('available_rooms', models.PositiveIntegerField(verbose_name='Количество доступных комнат')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('accommodation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.accommodationtype', verbose_name='Тип размещения')),
                ('bed_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.bedtype', verbose_name='Тип кроватей')),
                ('housing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.housingtype', verbose_name='Тип жилья')),
                ('price_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.pricerange', verbose_name='Ценовой диапазон')),
            ],
            options={
                'verbose_name': 'Гостиница',
                'verbose_name_plural': 'Гостиницы',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_name', models.CharField(max_length=255, verbose_name='Название места жительства')),
                ('image', models.ImageField(upload_to='images/housing/', verbose_name='Изображение места жительства')),
                ('description', models.TextField(verbose_name='Описание места жительства')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за сутки')),
                ('available_rooms', models.PositiveIntegerField(verbose_name='Количество доступных комнат')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('accommodation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.accommodationtype', verbose_name='Тип размещения')),
                ('bed_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.bedtype', verbose_name='Тип кроватей')),
                ('housing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.housingtype', verbose_name='Тип жилья')),
                ('price_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.pricerange', verbose_name='Ценовой диапазон')),
            ],
            options={
                'verbose_name': 'Апартаменты',
                'verbose_name_plural': 'Апартаменты',
            },
        ),
    ]
