# Generated by Django 4.2.3 on 2023-07-19 16:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_type', models.CharField(choices=[('Жилье целиком', 'Жилье целиком'), ('Комната', 'Комната'), ('Общая комната', 'Общая комната')], max_length=255, verbose_name='Тип размещения')),
            ],
            options={
                'verbose_name': 'Тип размещения',
                'verbose_name_plural': 'Типы размещения',
            },
        ),
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(choices=[('Односпальная', 'Односпальная'), ('Двуспальная', 'Двуспальная')], max_length=255, verbose_name='Тип кроватей')),
            ],
            options={
                'verbose_name': 'Тип кроватей',
                'verbose_name_plural': 'Типы кроватей',
            },
        ),
        migrations.CreateModel(
            name='HousingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.CharField(choices=[('Отели', 'Отели'), ('Хостелы', 'Хостелы'), ('Апартаменты', 'Апартаменты'), ('Гостиницы', 'Гостиницы')], max_length=50, verbose_name='Тип жилья')),
            ],
            options={
                'verbose_name': 'Тип жилья',
                'verbose_name_plural': 'Типы жилья',
            },
        ),
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.PositiveIntegerField(default=10, verbose_name='Минимум')),
                ('max_price', models.PositiveIntegerField(default=500, verbose_name='Максимум')),
            ],
            options={
                'verbose_name': 'Ценовой диапазон',
                'verbose_name_plural': 'Ценовые диапазоны',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_name', models.CharField(max_length=255, verbose_name='Название места жительства')),
                ('image', models.ImageField(upload_to='images/housing/', verbose_name='Изображение места жительства')),
                ('description', models.TextField(verbose_name='Описание места жительства')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за сутки')),
                ('available_rooms', models.PositiveIntegerField(verbose_name='Количество доступных комнат')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('accommodation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.accommodationtype', verbose_name='Тип размещения')),
                ('bed_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.bedtype', verbose_name='Тип кроватей')),
                ('housing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.housingtype', verbose_name='Тип жилья')),
                ('price_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.pricerange', verbose_name='Ценовой диапазон')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_name', models.CharField(max_length=255, verbose_name='Название места жительства')),
                ('image', models.ImageField(upload_to='images/housing/', verbose_name='Изображение места жительства')),
                ('description', models.TextField(verbose_name='Описание места жительства')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за сутки')),
                ('available_rooms', models.PositiveIntegerField(verbose_name='Количество доступных комнат')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('accommodation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.accommodationtype', verbose_name='Тип размещения')),
                ('bed_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.bedtype', verbose_name='Тип кроватей')),
                ('housing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.housingtype', verbose_name='Тип жилья')),
                ('price_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.pricerange', verbose_name='Ценовой диапазон')),
            ],
            options={
                'verbose_name': 'Хостел',
                'verbose_name_plural': 'Хостелы',
            },
        ),
        migrations.CreateModel(
            name='GuestHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_name', models.CharField(max_length=255, verbose_name='Название места жительства')),
                ('image', models.ImageField(upload_to='images/housing/', verbose_name='Изображение места жительства')),
                ('description', models.TextField(verbose_name='Описание места жительства')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за сутки')),
                ('available_rooms', models.PositiveIntegerField(verbose_name='Количество доступных комнат')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('accommodation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.accommodationtype', verbose_name='Тип размещения')),
                ('bed_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.bedtype', verbose_name='Тип кроватей')),
                ('housing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.housingtype', verbose_name='Тип жилья')),
                ('price_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.pricerange', verbose_name='Ценовой диапазон')),
            ],
            options={
                'verbose_name': 'Гостиница',
                'verbose_name_plural': 'Гостиницы',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_name', models.CharField(max_length=255, verbose_name='Название места жительства')),
                ('image', models.ImageField(upload_to='images/housing/', verbose_name='Изображение места жительства')),
                ('description', models.TextField(verbose_name='Описание места жительства')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за сутки')),
                ('available_rooms', models.PositiveIntegerField(verbose_name='Количество доступных комнат')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступность')),
                ('accommodation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.accommodationtype', verbose_name='Тип размещения')),
                ('bed_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.bedtype', verbose_name='Тип кроватей')),
                ('housing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.housingtype', verbose_name='Тип жилья')),
                ('price_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.pricerange', verbose_name='Ценовой диапазон')),
            ],
            options={
                'verbose_name': 'Апартаменты',
                'verbose_name_plural': 'Апартаменты',
            },
        ),
    ]
