# Generated by Django 4.2.3 on 2023-07-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelservice',
            name='price',
        ),
        migrations.AlterField(
            model_name='travelservice',
            name='service_name',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
