# Generated by Django 4.2.3 on 2023-07-23 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingamenities',
            options={},
        ),
        migrations.RemoveField(
            model_name='housing',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='min_and_max_price_per_night',
        ),
        migrations.AddField(
            model_name='housing',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='цена за ночь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housingamenities',
            name='housing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='housing_amenities', to='travel.housing'),
        ),
        migrations.AlterField(
            model_name='roomamenities',
            name='housing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_amenities', to='travel.housing'),
        ),
    ]
