# Generated by Django 4.2.3 on 2023-07-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingamenities',
            name='bell_staff_porter',
            field=models.BooleanField(default=False, verbose_name='Швейцар'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='buffet_breakfast',
            field=models.BooleanField(default=False, verbose_name='Завтрак "шведский стол"'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='currency_exchange',
            field=models.BooleanField(default=False, verbose_name='Обмен валюты'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='dry_cleaning',
            field=models.BooleanField(default=False, verbose_name='Сухая чистка'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='facial_treatments',
            field=models.BooleanField(default=False, verbose_name='Процедуры для лица'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='foot_massage',
            field=models.BooleanField(default=False, verbose_name='Массаж ног'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='free_instant_coffee',
            field=models.BooleanField(default=False, verbose_name='Бесплатный растворимый кофе'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='free_tea',
            field=models.BooleanField(default=False, verbose_name='Бесплатный чай'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='full_body_massage',
            field=models.BooleanField(default=False, verbose_name='Массаж всего тела'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='hammam',
            field=models.BooleanField(default=False, verbose_name='Хаммам'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='happy_hour',
            field=models.BooleanField(default=False, verbose_name='Счастливый час'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='head_massage',
            field=models.BooleanField(default=False, verbose_name='Массаж головы'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='individual_check_in_check_out',
            field=models.BooleanField(default=False, verbose_name='Индивидуальная регистрация заезда/отъезда'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='internet_business_center',
            field=models.BooleanField(default=False, verbose_name='Бизнес-центр с доступом в Интернет'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='manual_massage',
            field=models.BooleanField(default=False, verbose_name='Ручной массаж'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='massage',
            field=models.BooleanField(default=False, verbose_name='Массаж'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='neck_massage',
            field=models.BooleanField(default=False, verbose_name='Массаж шеи'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='shoe_shine',
            field=models.BooleanField(default=False, verbose_name='Чистка обуви'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='special_diet_menu',
            field=models.BooleanField(default=False, verbose_name='Специальное диетическое меню'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='steam_room',
            field=models.BooleanField(default=False, verbose_name='Паровая комната'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='taxi_service',
            field=models.BooleanField(default=False, verbose_name='Служба такси'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='bath_or_shower',
            field=models.BooleanField(default=False, verbose_name='Ванна/душ'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='bidet',
            field=models.BooleanField(default=False, verbose_name='Биде'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='bottled_water',
            field=models.BooleanField(default=False, verbose_name='Бутилированная вода'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='cable_satellite_tv',
            field=models.BooleanField(default=False, verbose_name='Кабельное / спутниковое телевидение'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='coffee_teapot',
            field=models.BooleanField(default=False, verbose_name='Кофеварка/чайник'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='connecting_rooms_available',
            field=models.BooleanField(default=False, verbose_name='Доступны смежные номера'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='flat_screen_tv',
            field=models.BooleanField(default=False, verbose_name='Телевизор с плоским экраном'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='laptop_safe_box',
            field=models.BooleanField(default=False, verbose_name='Сейф для ноутбука'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='minibar',
            field=models.BooleanField(default=False, verbose_name='Минибар'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='private_bathroom',
            field=models.BooleanField(default=False, verbose_name='Частные ванные комнаты'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='room_cleaning',
            field=models.BooleanField(default=False, verbose_name='Уборка'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='room_service',
            field=models.BooleanField(default=False, verbose_name='Обслуживание номеров'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='safe',
            field=models.BooleanField(default=False, verbose_name='Безопасный'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='sitting_area',
            field=models.BooleanField(default=False, verbose_name='Зона отдыха'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='telephone',
            field=models.BooleanField(default=False, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='wake_up_service',
            field=models.BooleanField(default=False, verbose_name='Услуга будильник / будильник'),
        ),
        migrations.AddField(
            model_name='roomamenities',
            name='work_desk',
            field=models.BooleanField(default=False, verbose_name='Рабочий стол'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='housing_type',
            field=models.CharField(choices=[('Отели', 'Отели'), ('Хостелы', 'Хостелы'), ('Апартаменты', 'Апартаменты'), ('Гостевые дома', 'Гостевые дома'), ('Санатории', 'Санатории')], max_length=255, verbose_name='Тип жилья'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='location',
            field=models.CharField(max_length=255, verbose_name='местоположение жилища'),
        ),
    ]
