# Generated by Django 4.2.3 on 2023-08-01 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingamenities',
            options={'verbose_name': 'Удобства в объекте', 'verbose_name_plural': 'Удобства в объекте'},
        ),
        migrations.RemoveField(
            model_name='housingamenities',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='housingamenities',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='housing',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housing',
            name='check_in_time_end',
            field=models.TimeField(null=True, verbose_name='Заезд До'),
        ),
        migrations.AddField(
            model_name='housing',
            name='check_in_time_start',
            field=models.TimeField(null=True, verbose_name='Заезд С'),
        ),
        migrations.AddField(
            model_name='housing',
            name='check_out_time_end',
            field=models.TimeField(null=True, verbose_name='Отъезд До'),
        ),
        migrations.AddField(
            model_name='housing',
            name='check_out_time_start',
            field=models.TimeField(null=True, verbose_name='Отъезд С'),
        ),
        migrations.AddField(
            model_name='housing',
            name='parking_service',
            field=models.CharField(choices=[('free', 'Да, бесплатно'), ('paid', 'Да, платно'), ('no', 'Нет')], default='no', max_length=10, verbose_name='Услуги парковки'),
        ),
        migrations.AddField(
            model_name='housing',
            name='region',
            field=models.CharField(choices=[('Бишкек', 'Бишкек'), ('Джалал-Абад', 'Джалал-Абад'), ('Иссык-Куль', 'Иссык-Куль'), ('Ош', 'Ош'), ('Нарын', 'Нарын'), ('Талас', 'Талас'), ('Баткен', 'Баткен')], default=1, max_length=255, verbose_name='Область'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housing',
            name='stars',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Количество звезд'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='allow_children',
            field=models.BooleanField(default=False, verbose_name='C детьми?'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='allow_pets',
            field=models.BooleanField(default=False, verbose_name='C домашними животными'),
        ),
        migrations.AddField(
            model_name='housingamenities',
            name='kids_playground',
            field=models.BooleanField(default=False, verbose_name='Детская площадка'),
        ),
    ]
