# Generated by Django 4.2.3 on 2023-08-08 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ratings_given'),
        ),
        migrations.AddField(
            model_name='housereservation',
            name='housing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travel.housing', verbose_name='Жилье'),
        ),
        migrations.AddField(
            model_name='housereservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
