# Generated by Django 4.2.3 on 2023-08-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='booking_type',
            field=models.CharField(choices=[('Без банковской карты', 'Без банковской карты'), ('Бесплатная отмена', 'Бесплатная отмена')], default='Без банковской карты', max_length=50, verbose_name='Бронирование'),
        ),
        migrations.AddField(
            model_name='housing',
            name='payment_type',
            field=models.CharField(choices=[('К оплате сейчас', 'К оплате сейчас'), ('Предоплата', 'Предоплата'), ('Оплата наличными', 'Оплата наличными')], default='К оплате сейчас', max_length=50, verbose_name='Оплата'),
        ),
    ]
