# Generated by Django 4.2.3 on 2023-08-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_housingamenities_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='человеко-понятный url'),
        ),
    ]
