# Generated by Django 4.2.3 on 2023-08-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_housing_booking_type_housing_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='booking_type',
        ),
        migrations.AddField(
            model_name='housing',
            name='free_cancellation',
            field=models.BooleanField(default=False, verbose_name='Бесплатная отмена'),
        ),
        migrations.AddField(
            model_name='housing',
            name='without_credit_card',
            field=models.BooleanField(default=True, verbose_name='Без банковской карты'),
        ),
    ]
