# Generated by Django 4.2.3 on 2023-08-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_housing_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='images',
        ),
        migrations.AddField(
            model_name='housing',
            name='images',
            field=models.ManyToManyField(related_name='housing_images', to='travel.housingimage'),
        ),
    ]
