# Generated by Django 4.2.3 on 2023-08-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomimage',
            old_name='room_image',
            new_name='image',
        ),
    ]
