# Generated by Django 4.2.3 on 2023-08-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='parking_location',
            field=models.CharField(blank=True, choices=[('On-site', 'На территории'), ('Off-site', 'За территорией')], max_length=50, null=True, verbose_name='Местонахождение парковки'),
        ),
    ]
