# Generated by Django 4.2.3 on 2023-07-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_remove_travelservice_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelservice',
            name='service_name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
