# Generated by Django 4.2.3 on 2023-07-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_housingamenities_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='image',
            field=models.ImageField(upload_to='images/housing/', verbose_name='Изображение места жительства'),
        ),
    ]
