# Generated by Django 4.2.3 on 2023-08-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housing',
            options={'verbose_name': 'Место жительства', 'verbose_name_plural': 'Места жительства'},
        ),
        migrations.AlterField(
            model_name='housing',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='image',
            field=models.ImageField(upload_to='images/housing', verbose_name='Изображение'),
        ),
    ]
