# Generated by Django 4.2.3 on 2023-08-03 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='housing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.housing', verbose_name='ratings_received'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('Замечательно', 'Замечательно'), ('Отлично', 'Отлично'), ('Хорошо', 'Хорошо'), ('Неплохо', 'Неплохо'), ('Не оценено', 'Не оценено')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ratings_given'),
        ),
    ]
