# Generated by Django 4.2.3 on 2023-08-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_housereservation_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/housing/', verbose_name='Изображение места жительства'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='food_type',
            field=models.CharField(choices=[('all-inclusive', 'Все включено'), ('Breakfast included', 'Завтрак включен'), ('Not included', 'Не включено'), ('With own kitchen', 'С собственной кухней')], default='Не включено', max_length=50, verbose_name='Тип питания'),
        ),
    ]
