# Generated by Django 4.2.3 on 2023-08-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_initial'),
        ('travel', '0003_alter_housingreservation_check_in_date_and_more'),
    ]

    operations = [
    ]
