# Generated by Django 4.2.3 on 2023-08-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_housing_options_alter_housing_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housereservation',
            options={'verbose_name': 'Бронь места жительста', 'verbose_name_plural': 'Бронь мест жительст'},
        ),
    ]
