# Generated by Django 4.2.3 on 2023-08-06 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_housing_parking_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housereservation',
            name='housing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.housing', verbose_name='Жилье'),
        ),
    ]
