# Generated by Django 4.2.3 on 2023-09-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_room_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='images',
        ),
    ]
