# Generated by Django 4.2.3 on 2023-08-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_housingimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housefavorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
    ]
