# Generated by Django 4.2.3 on 2023-08-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_housing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
    ]
