# Generated by Django 4.2.3 on 2023-08-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_housing_booking_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='free_cancellation',
            field=models.BooleanField(choices=[('Нет', 'Нет'), ('Да', 'Да')], default=False, verbose_name='Бесплатная отмена'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='without_credit_card',
            field=models.BooleanField(choices=[('Нет', 'Нет'), ('Да', 'Да')], default=True, verbose_name='Без банковской карты'),
        ),
    ]
