# Generated by Django 4.2.3 on 2023-08-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_housing_images_housing_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='images',
        ),
        migrations.AddField(
            model_name='housing',
            name='images',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
