# Generated by Django 4.2.3 on 2023-08-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_housingamenities_air_conditioner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housingamenities',
            old_name='amenities',
            new_name='housing_amenities',
        ),
        migrations.RenameField(
            model_name='roomamenities',
            old_name='amenities',
            new_name='room_amenities',
        ),
    ]
