# Generated by Django 4.2.3 on 2023-08-04 11:47

import datetime
import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_housereservation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housing',
            old_name='parking_service',
            new_name='parking',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='location',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='housing',
            name='breakfast_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость завтрака в US$ (с человека за ночь)'),
        ),
        migrations.AddField(
            model_name='housing',
            name='breakfast_included',
            field=models.BooleanField(default=False, verbose_name='Завтрак включен в стоимость проживания?'),
        ),
        migrations.AddField(
            model_name='housing',
            name='breakfast_offered',
            field=models.BooleanField(default=False, verbose_name='Вы предлагаете гостям завтрак?'),
        ),
        migrations.AddField(
            model_name='housing',
            name='breakfast_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Asian', 'Азиатский'), ('Continental', 'Континентальный'), ('Swedish', 'Шведский')], max_length=100, verbose_name='Какой тип завтрака вы предлагаете?'),
        ),
        migrations.AddField(
            model_name='housing',
            name='cancellation_policy',
            field=models.CharField(choices=[('before_00_00_on_check_in_day', 'До 00:00 в день заезда'), ('anytime', 'В любое время'), ('full_cost', 'Отмена за полную стоимость')], default=1, max_length=50, verbose_name='Бесплатная отмена '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housing',
            name='children_allowed',
            field=models.BooleanField(default=False, verbose_name='Можно ли проживать с детьми?'),
        ),
        migrations.AddField(
            model_name='housing',
            name='double_bed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество двуспальных кроватей'),
        ),
        migrations.AddField(
            model_name='housing',
            name='full_cancellation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Полная стоимость'),
        ),
        migrations.AddField(
            model_name='housing',
            name='king_bed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество широких (king-size) кроватей'),
        ),
        migrations.AddField(
            model_name='housing',
            name='max_guest_capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Максимальная вместимость гостей в номере'),
        ),
        migrations.AddField(
            model_name='housing',
            name='num_rooms',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Количество комнат в номере'),
        ),
        migrations.AddField(
            model_name='housing',
            name='payment',
            field=models.CharField(choices=[('Pay now', 'К оплате сейчас'), ('Prepayment', 'Предоплата'), ('Cash payment', 'Оплата наличными')], default='К оплате сейчас', max_length=50, verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='housing',
            name='pet_fee',
            field=models.BooleanField(default=False, verbose_name='Берете ли вы плату за домашних животных?'),
        ),
        migrations.AddField(
            model_name='housing',
            name='pets_allowed',
            field=models.BooleanField(default=False, verbose_name='Можно ли проживать с домашними животными?'),
        ),
        migrations.AddField(
            model_name='housing',
            name='queen_bed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество широких (queen-size) кроватей'),
        ),
        migrations.AddField(
            model_name='housing',
            name='room_area',
            field=models.PositiveIntegerField(default=1, verbose_name='Площадь комнаты(м²)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housing',
            name='room_name',
            field=models.CharField(choices=[('1_bedroom_double', 'Двухместный номер с 1 кроватью'), ('2_bedroom_twin', 'Двухместный с 2 отдельными кроватями'), ('1_or_2_bedroom', 'Двухместный номер с 1 кроватью или 2 отдельными кроватями'), ('luxury', 'Люкс'), ('3_bedroom', 'Трехместный номер'), ('family', 'Семейный'), ('deluxe', 'Делюкс'), ('4_bedroom', 'Четырехместный'), ('penthouse', 'Пентхаус'), ('connecting', 'Коннектирующийся номер'), ('business', 'Бизнес'), ('royal_luxury', 'Королевский люкс'), ('economy', 'Эконом'), ('standard', 'Стандартный')], default=1, max_length=50, verbose_name='название номера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housing',
            name='single_bed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество односпальных кроватей'),
        ),
        migrations.AddField(
            model_name='housing',
            name='smoking_allowed',
            field=models.BooleanField(default=False, verbose_name='Разрешено ли курение в комнате'),
        ),
        migrations.AddField(
            model_name='housing',
            name='sofa_bed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество диван-кроватей'),
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='check_in_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 8, 4))], verbose_name='Заезд'),
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='check_out_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 8, 4))], verbose_name='Выезд'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='accommodation_type',
            field=models.CharField(choices=[('Entire place', 'Жилье целиком'), ('Room', 'Комната'), ('Shared room', 'Общая комната')], max_length=50, verbose_name='Тип размещения'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='bed_type',
            field=models.CharField(choices=[('Single', 'Отдельные'), ('Double', 'Двуспальная'), ('Kingsize', 'Kingsize'), ('Queensize', 'Queensize'), ('Диван-кровать', 'Диван-кровать')], max_length=50, verbose_name='Тип кроватей'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='bedrooms',
            field=models.CharField(choices=[('1 bedroom', '1 спальня'), ('2 bedrooms', '2 спальни'), ('More than 3 bedrooms', 'Больше 3 спален')], max_length=50, verbose_name='Количество спален'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='check_in_time_end',
            field=models.TimeField(choices=[('0', '00:00'), ('0', '01:00'), ('0', '02:00'), ('0', '03:00'), ('0', '04:00'), ('0', '05:00'), ('0', '06:00'), ('0', '07:00'), ('0', '08:00'), ('0', '09:00'), ('0', '10:00'), ('0', '11:00'), ('0', '12:00'), ('0', '13:00'), ('0', '14:00'), ('0', '15:00'), ('0', '16:00'), ('0', '17:00'), ('0', '18:00'), ('0', '19:00'), ('0', '20:00'), ('0', '21:00'), ('0', '22:00'), ('0', '23:00')], verbose_name='Заезд До'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='check_in_time_start',
            field=models.TimeField(choices=[('0', '00:00'), ('0', '01:00'), ('0', '02:00'), ('0', '03:00'), ('0', '04:00'), ('0', '05:00'), ('0', '06:00'), ('0', '07:00'), ('0', '08:00'), ('0', '09:00'), ('0', '10:00'), ('0', '11:00'), ('0', '12:00'), ('0', '13:00'), ('0', '14:00'), ('0', '15:00'), ('0', '16:00'), ('0', '17:00'), ('0', '18:00'), ('0', '19:00'), ('0', '20:00'), ('0', '21:00'), ('0', '22:00'), ('0', '23:00')], verbose_name='Заезд С'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='check_out_time_end',
            field=models.TimeField(choices=[('0', '00:00'), ('0', '01:00'), ('0', '02:00'), ('0', '03:00'), ('0', '04:00'), ('0', '05:00'), ('0', '06:00'), ('0', '07:00'), ('0', '08:00'), ('0', '09:00'), ('0', '10:00'), ('0', '11:00'), ('0', '12:00'), ('0', '13:00'), ('0', '14:00'), ('0', '15:00'), ('0', '16:00'), ('0', '17:00'), ('0', '18:00'), ('0', '19:00'), ('0', '20:00'), ('0', '21:00'), ('0', '22:00'), ('0', '23:00')], verbose_name='Отъезд До'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='check_out_time_start',
            field=models.TimeField(choices=[('0', '00:00'), ('0', '01:00'), ('0', '02:00'), ('0', '03:00'), ('0', '04:00'), ('0', '05:00'), ('0', '06:00'), ('0', '07:00'), ('0', '08:00'), ('0', '09:00'), ('0', '10:00'), ('0', '11:00'), ('0', '12:00'), ('0', '13:00'), ('0', '14:00'), ('0', '15:00'), ('0', '16:00'), ('0', '17:00'), ('0', '18:00'), ('0', '19:00'), ('0', '20:00'), ('0', '21:00'), ('0', '22:00'), ('0', '23:00')], verbose_name='Отъезд С'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='food_type',
            field=models.CharField(choices=[('All-inclusive', 'Все включено'), ('Breakfast included', 'Завтрак включен'), ('Not included', 'Не включено'), ('With own kitchen', 'С собственной кухней')], default='Не включено', max_length=50, verbose_name='Тип питания'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='free_cancellation',
            field=models.BooleanField(default=False, verbose_name='Бесплатная отмена'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='housing_amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('free_internet', 'Бесплатный интернет'), ('spa_services', 'Спа услуги'), ('restaurant', 'Ресторан'), ('Sports Hall', 'Спортивный зал'), ('pool', 'Бассейн'), ('airport_transfer', 'Трансфер от/до аэропорта'), ('fitness', 'Фитнес'), ('pet_allowed', 'Можно с питомцами'), ('indoor_pool', 'Крытый бассейн'), ('non_smoking_rooms', 'Номера для некурящих'), ('wifi', 'Wifi'), ('room_service', 'Доставка еды и напитков в номер'), ('coffee_teapot', 'Кофеварка/чайник'), ('bar', 'Бар'), ('garden_furniture', 'Садовая мебель'), ('sun_terrace', 'Терасса для загара'), ('garden', 'Сад'), ('wine_champagne', 'Вино/шампанское (платно)'), ('kids_menu', 'Детское меню (платно)'), ('breakfast_in_room', 'Завтрак в номер'), ('breakfast_paid', 'Завтрак включен в стоимость проживания?'), ('free_wifi', 'Бесплатный Wi-Fi на территории всего отеля'), ('daily_cleaning', 'Ежедневная уборка'), ('laundry_service', 'Услуги по глажению одежды (платно)'), ('paid_cleaning', 'Химчистка (платно)'), ('paid_laundry', 'Прачечная (платно)'), ('fax_xerox', 'Факс/ксерокопирование (платно)'), ('conference_banquet_hall', 'Конференц-зал/банкетный зал (платно)'), ('fire_extinguishers', 'Огнетушители'), ('smoke_detectors', 'Датчики дыма'), ('outdoor_surveillance', 'Видеонаблюдения снаружи здания'), ('public_areas_surveillance', 'Видеонаблюдения в местах общего пользования'), ('security_alarm', 'Охранная сигнализация'), ('full_time_security', 'Круглосуточная охрана'), ('safe', 'Сейф'), ('invoices_issued', 'Выдаются счета'), ('lockers', 'Запирающиеся шкафчики'), ('concierge_service', 'Услуги консьержа'), ('atm_on_site', 'Банкомат на территории отеля'), ('luggage_storage', 'Хранение багажа'), ('express_check_in', 'Ускоренная регистрация'), ('full_time_front_desk', 'Круглосуточная стойка регистрации'), ('transfer_paid', 'Трансфер (платно)'), ('food_delivery_to_room_paid', 'Доставка продуктов питания в номер (платно)'), ('smoking_areas', 'Места для курения'), ('air_conditioner', 'Кондиционер'), ('heating', 'Отопление'), ('car_rental', 'Прокат автомобилей'), ('packed_lunches', 'Упакованные ланчи'), ('ironing_facilities', 'Гладильные принадлежности'), ('buffet_breakfast', 'Завтрак "шведский стол"'), ('free_instant_coffee', 'Бесплатный растворимый кофе'), ('free_tea', 'Бесплатный чай'), ('happy_hour', 'Счастливый час'), ('special_diet_menu', 'Специальное диетическое меню'), ('taxi_service', 'Служба такси'), ('internet_business_center', 'Бизнес-центр с доступом в Интернет'), ('facial_treatments', 'Процедуры для лица'), ('foot_massage', 'Массаж ног'), ('full_body_massage', 'Массаж всего тела'), ('hammam', 'Хаммам'), ('manual_massage', 'Ручной массаж'), ('head_massage', 'Массаж головы'), ('massage', 'Массаж'), ('neck_massage', 'Массаж шеи'), ('steam_room', 'Паровая комната'), ('currency_exchange', 'Обмен валюты'), ('bell_staff_porter', 'Швейцар'), ('individual_check_in_check_out', 'Индивидуальная регистрация заезда/отъезда'), ('dry_cleaning', 'Сухая чистка'), ('shoe_shine', 'Чистка обуви'), ('kids_playground', 'Детская площадка'), ('allow_children', 'C детьми?'), ('allow_pets', 'C домашними животными'), ('pets_paid', 'Берете ли вы плату за домашних животных?'), ('Parking lot', 'Парковка')], max_length=100, verbose_name='Удобства в объекте'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='housing_type',
            field=models.CharField(choices=[('Hotels', 'Отели'), ('Hostels', 'Хостелы'), ('Apartments', 'Квартиры'), ('Guesthouses', 'Гостевые дома'), ('Sanatoriums', 'Санатории')], max_length=50, verbose_name='Тип жилья'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='parking_location',
            field=models.CharField(blank=True, choices=[('On-site', 'На территории'), ('Off-site', 'За территорией')], max_length=50, null=True, verbose_name='Местонахождение парковки'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='region',
            field=models.CharField(choices=[('Бишкек', 'Бишкек'), ('Джалал-Абад', 'Джалал-Абад'), ('Иссык-Куль', 'Иссык-Куль'), ('Ош', 'Ош'), ('Нарын', 'Нарын'), ('Талас', 'Талас'), ('Баткен', 'Баткен')], max_length=50, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='room_amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('air_conditioner', 'Кондиционер'), ('hair_dryer', 'Фен'), ('washing_machine', 'Стиральная машина'), ('iron', 'Утюг'), ('dryer', 'Сушильная машина'), ('fridge', 'Холодильник'), ('tv', 'Телевизор'), ('microwave', 'Микроволновка'), ('heating', 'Отопление'), ('sofa_bed', 'Диван-кровать'), ('folding_bed', 'Раскладная кровать'), ('Double bed', 'Двуспальная кровать'), ('wardrobe', 'Шкаф или гардероб'), ('linen', 'Белье'), ('clothes_hanger', 'Вешалка для одежды'), ('complimentary_toiletries', 'Бесплатные туалетно-косметические принадлежности'), ('toilet_paper', 'Туалетная бумага'), ('kitchen_utensils', 'Кухонные принадлежности'), ('electric_kettle', 'Электрический чайник'), ('city_view', 'Вид на город'), ('garden_view', 'Вид на сад'), ('high_toilet', 'Высокий туалет'), ('toilet_with_handles', 'Туалет с поручнями'), ('accessible_to_disabled_guests', 'Подходит для гостей с ограниченными возможностями'), ('work_desk', 'Рабочий стол'), ('room_cleaning', 'Уборка'), ('coffee_teapot', 'Кофеварка/чайник'), ('cable_satellite_tv', 'Кабельное / спутниковое телевидение'), ('bidet', 'Биде'), ('connecting_rooms_available', 'Доступны смежные номера'), ('room_service', 'Обслуживание номеров'), ('safe', 'Безопасный'), ('sitting_area', 'Зона отдыха'), ('telephone', 'Телефон'), ('bottled_water', 'Бутилированная вода'), ('Safe', 'Сейф'), ('laptop_safe_box', 'Сейф для ноутбука'), ('private_bathroom', 'Частные ванные комнаты'), ('wake_up_service', 'Услуга будильник / будильник'), ('minibar', 'Минибар'), ('flat_screen_tv', 'Телевизор с плоским экраном'), ('bath_or_shower', 'Ванна/душ'), ('Dressers', 'Комоды'), ('Mini kitchen', 'Мини кухня'), ('Fireplace', 'Камин'), ('Appetizers', 'Закуски'), ('2 rooms', '2 комнаты')], max_length=100, verbose_name='Удобства в номере'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='without_credit_card',
            field=models.BooleanField(default=True, verbose_name='Без банковской карты'),
        ),
    ]
