# Generated by Django 4.2.3 on 2023-08-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_rating_housing_alter_rating_rating_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(choices=[('9+: Замечательно', '9+: Замечательно'), ('8+: Отлично', '8+: Отлично'), ('7+: Хорошо', '7+: Хорошо'), ('5+: Неплохо', '5+: Неплохо'), ('0:  Не оценено', '0:Не оценено')], default='0', max_length=20),
        ),
    ]
