# Generated by Django 4.2.3 on 2023-09-15 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_housing_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='travel.housingimage'),
        ),
    ]
