# Generated by Django 4.2.3 on 2023-08-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_remove_housing_images_housing_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='images',
        ),
    ]
