# Generated by Django 4.2.3 on 2023-07-17 16:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0004_alter_travelservice_options_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Signal',
        ),
    ]
