# Generated by Django 4.2.3 on 2023-08-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_rename_parking_service_housing_parking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='full_cancellation_cost',
        ),
        migrations.AlterField(
            model_name='housing',
            name='cancellation_policy',
            field=models.CharField(choices=[('before_00_00_on_check_in_day', 'До 00:00 в день заезда'), ('anytime', 'В любое время')], max_length=50, verbose_name='Правила бесплатной отмены'),
        ),
    ]
