# Generated by Django 4.2.3 on 2023-08-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_rename_outside_room_amenities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='amenities',
            new_name='outside',
        ),
        migrations.AddField(
            model_name='housing',
            name='car_rental',
            field=models.BooleanField(default=False, verbose_name='Прокат автомобиля'),
        ),
        migrations.AddField(
            model_name='housing',
            name='children_playground',
            field=models.BooleanField(default=False, verbose_name='Детская площадка'),
        ),
        migrations.AddField(
            model_name='housing',
            name='gym',
            field=models.BooleanField(default=False, verbose_name='Спортивный зал'),
        ),
    ]
