# Generated by Django 4.2.3 on 2023-08-06 07:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_housefavorite_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housereservation',
            name='check_in_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 8, 6))], verbose_name='Заезд'),
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='check_out_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 8, 6))], verbose_name='Выезд'),
        ),
    ]
