# Generated by Django 4.2.3 on 2023-07-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_housing_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='bedrooms',
            field=models.CharField(choices=[('1 спальня', '1 спальня'), ('2 спальни', '2 спальни'), ('Больше 3 спален', 'Больше 3 спален')], default='Не включено', max_length=255, verbose_name='Количество спален'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='food_type',
            field=models.CharField(choices=[('Все включено', 'Все включено'), ('Завтрак включен', 'Завтрак включен'), ('Не включено', 'Не включено'), ('С собственной кухней', 'С собственной кухней')], default='Не включено', max_length=255, verbose_name='Тип питания'),
        ),
    ]
