# Generated by Django 4.2.3 on 2023-08-01 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_remove_roomamenities_housing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='stars',
            field=models.PositiveIntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****'), (0, 'Без звезд')], default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Количество звезд'),
        ),
    ]
