# Generated by Django 4.2.3 on 2023-08-27 05:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_housingreservation_check_in_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingreservation',
            name='infants',
        ),
        migrations.RemoveField(
            model_name='housingreservation',
            name='pets',
        ),
        migrations.AlterField(
            model_name='housingreservation',
            name='check_in_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 8, 27))], verbose_name='Заезд'),
        ),
        migrations.AlterField(
            model_name='housingreservation',
            name='check_out_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 8, 27))], verbose_name='Выезд'),
        ),
    ]
