# Generated by Django 4.2.3 on 2023-08-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_housingreservation_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Free_cancellation_anytime',
            field=models.BooleanField(default=False, verbose_name='Бесплатное отмена в любое время'),
        ),
    ]
