# Generated by Django 4.2.3 on 2023-08-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_wishlistalbum_delete_wishlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistalbum',
            name='user',
        ),
        migrations.DeleteModel(
            name='HouseFavorite',
        ),
        migrations.DeleteModel(
            name='WishlistAlbum',
        ),
    ]
