# Generated by Django 4.2.3 on 2023-08-10 12:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0005_alter_review_housing_alter_room_housing_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='HousingReview',
        ),
    ]
