# Generated by Django 4.2.3 on 2023-08-07 14:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_remove_housing_image_alter_housing_housing_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('air_conditioner', 'Кондиционер'), ('hair_dryer', 'Фен'), ('washing_machine', 'Стиральная машина'), ('iron', 'Утюг'), ('dryer', 'Сушильная машина'), ('fridge', 'Холодильник'), ('tv', 'Телевизор'), ('microwave', 'Микроволновка'), ('heating', 'Отопление'), ('sofa_bed', 'Диван-кровать'), ('folding_bed', 'Раскладная кровать'), ('Double bed', 'Двуспальная кровать'), ('wardrobe', 'Шкаф или гардероб'), ('linen', 'Белье'), ('clothes_hanger', 'Вешалка для одежды'), ('complimentary_toiletries', 'Бесплатные туалетно-косметические принадлежности'), ('toilet_paper', 'Туалетная бумага'), ('kitchen_utensils', 'Кухонные принадлежности'), ('electric_kettle', 'Электрический чайник'), ('city_view', 'Вид на город'), ('garden_view', 'Вид на сад'), ('high_toilet', 'Высокий туалет'), ('toilet_with_handles', 'Туалет с поручнями'), ('accessible_to_disabled_guests', 'Подходит для гостей с ограниченными возможностями'), ('work_desk', 'Рабочий стол'), ('room_cleaning', 'Уборка'), ('coffee_teapot', 'Кофеварка/чайник'), ('cable_satellite_tv', 'Кабельное / спутниковое телевидение'), ('bidet', 'Биде'), ('connecting_rooms_available', 'Доступны смежные номера'), ('room_service', 'Обслуживание номеров'), ('safe', 'Безопасный'), ('sitting_area', 'Зона отдыха'), ('telephone', 'Телефон'), ('bottled_water', 'Бутилированная вода'), ('Safe', 'Сейф'), ('laptop_safe_box', 'Сейф для ноутбука'), ('private_bathroom', 'Частные ванные комнаты'), ('wake_up_service', 'Услуга будильник / будильник'), ('minibar', 'Минибар'), ('flat_screen_tv', 'Телевизор с плоским экраном'), ('bath_or_shower', 'Ванна/душ'), ('Dressers', 'Комоды'), ('Mini kitchen', 'Мини кухня'), ('Fireplace', 'Камин'), ('Appetizers', 'Закуски'), ('2 rooms', '2 комнаты')], max_length=100, verbose_name='Удобства номера'),
        ),
    ]
