# Generated by Django 4.2.3 on 2023-08-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='housing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='travel.housing'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[(9, 'Замечательно'), (8, 'Отлично'), (7, 'Хорошо'), (5, 'Неплохо'), (0, 'Не оценено')], default='0', max_length=20),
        ),
    ]
