# Generated by Django 4.2.3 on 2023-08-06 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_housereservation_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housereservation',
            name='housing',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='travel.housing', verbose_name='Жилье'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='infants',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Младенцы(младше 2)'),
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='pets',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Домашние животные'),
        ),
    ]
