# Generated by Django 4.2.3 on 2023-08-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_remove_housing_breakfast_cost_usd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='image',
        ),
    ]
