# Generated by Django 4.2.3 on 2023-09-01 09:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_room_free_cancellation_anytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='location',
            field=models.CharField(default=2, max_length=100, verbose_name='Локация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housingreservation',
            name='check_in_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 9, 1))], verbose_name='Заезд'),
        ),
        migrations.AlterField(
            model_name='housingreservation',
            name='check_out_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 9, 1))], verbose_name='Выезд'),
        ),
    ]
