# Generated by Django 4.2.3 on 2023-07-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_signal_options_remove_signal_is_read_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='s_read',
            new_name='is_read',
        ),
    ]
