# Generated by Django 4.2.3 on 2023-08-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_rename_review_housingreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingreview',
            name='housing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.housing', verbose_name='Название места жительства'),
        ),
    ]
