# Generated by Django 4.2.3 on 2023-08-06 16:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_housereservation_housing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='breakfast_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Asian', 'Азиатский'), ('Continental', 'Континентальный'), ('Swedish', 'Шведский')], max_length=100, null=True, verbose_name='Какой тип завтрака вы предлагаете?'),
        ),
    ]
