# Generated by Django 4.2.3 on 2023-08-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_remove_housingreservation_infants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='gym',
            field=models.BooleanField(default=False, verbose_name='Спортзал'),
        ),
    ]
