# Generated by Django 4.2.3 on 2023-07-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_rename_s_read_signal_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Когда написанно'),
        ),
    ]
