# Generated by Django 4.2.3 on 2023-09-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_housing_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='location',
        ),
    ]
