# Generated by Django 4.2.3 on 2023-09-02 08:59

import datetime
import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_remove_housing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='breakfast_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Национальный', 'Национальный'), ('Континентальный', 'Континентальный'), ('Шведский', 'Шведский')], max_length=100, null=True, verbose_name='Какой тип завтрака вы предлагаете?'),
        ),
        migrations.AlterField(
            model_name='housingreservation',
            name='check_in_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 9, 2))], verbose_name='Заезд'),
        ),
        migrations.AlterField(
            model_name='housingreservation',
            name='check_out_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 9, 2))], verbose_name='Выезд'),
        ),
        migrations.AlterField(
            model_name='room',
            name='kitchen',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Электрический чайник', 'Электрический чайник'), ('Микроволновка', 'Микроволновка'), ('Обеденный стол', 'Обеденный стол'), ('Кофеварка', 'Кофеварка'), ('Mini-bar', 'Mini-bar'), ('Холодильник', 'Холодильник')], max_length=255, verbose_name='Кухня'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Двуспальная кровать', 'Двуспальная кровать'), ('Телевизор', 'Телевизор'), ('Стиральная машина', 'Стиральная машина'), ('Ванная комната', 'Ванная комната'), ('Утюг', 'Утюг'), ('Сейф', 'Сейф'), ('Телефон', 'Телефон'), ('Комоды', 'Комоды'), ('Шкафы', 'Шкафы'), ('Мини кухня', 'Мини кухня'), ('Камин', 'Камин'), ('Закуски', 'Закуски')], max_length=255, verbose_name='Удобства'),
        ),
    ]
