# Generated by Django 4.2.3 on 2023-08-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_housing_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='images',
            field=models.ImageField(upload_to='', verbose_name='Пути к изображениям места жительства'),
        ),
    ]
