# Generated by Django 4.2.3 on 2023-08-10 14:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0008_rename_guesthouse_house_alter_house_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseReservation',
            new_name='HousingReservation',
        ),
    ]
