# Generated by Django 4.2.3 on 2023-08-08 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_remove_housing_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingimage',
            options={'verbose_name': 'Изображение места жительства', 'verbose_name_plural': 'Изображения места жительства'},
        ),
        migrations.RemoveField(
            model_name='housingimage',
            name='image_type',
        ),
        migrations.AlterField(
            model_name='housingimage',
            name='housing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_images', to='travel.housing'),
        ),
        migrations.AlterField(
            model_name='housingimage',
            name='image',
            field=models.ImageField(upload_to='images/housing/', verbose_name='Изображение места жительства'),
        ),
    ]
