# Generated by Django 4.2.3 on 2023-08-07 20:55

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_housing_housing_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housereservation',
            name='children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Дети(от 2-12 лет)'),
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='housing',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel.housing', verbose_name='Жилье'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='infants',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Младенцы(младше 2)'),
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='pets',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Домашние животные'),
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='teens',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Подростки(от 13-18 лет)'),
        ),
        migrations.AlterField(
            model_name='housingimage',
            name='image',
            field=models.ImageField(default=1, upload_to='images/housing/', verbose_name='Изображение места жительства'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('air_conditioner', 'Кондиционер'), ('hair_dryer', 'Фен'), ('washing_machine', 'Стиральная машина'), ('iron', 'Утюг'), ('dryer', 'Сушильная машина'), ('fridge', 'Холодильник'), ('tv', 'Телевизор'), ('microwave', 'Микроволновка'), ('heating', 'Отопление'), ('sofa_bed', 'Диван-кровать'), ('folding_bed', 'Раскладная кровать'), ('Double bed', 'Двуспальная кровать'), ('wardrobe', 'Шкаф или гардероб'), ('linen', 'Белье'), ('clothes_hanger', 'Вешалка для одежды'), ('complimentary_toiletries', 'Бесплатные туалетно-косметические принадлежности'), ('toilet_paper', 'Туалетная бумага'), ('kitchen_utensils', 'Кухонные принадлежности'), ('electric_kettle', 'Электрический чайник'), ('city_view', 'Вид на город'), ('garden_view', 'Вид на сад'), ('high_toilet', 'Высокий туалет'), ('toilet_with_handles', 'Туалет с поручнями'), ('accessible_to_disabled_guests', 'Подходит для гостей с ограниченными возможностями'), ('work_desk', 'Рабочий стол'), ('room_cleaning', 'Уборка'), ('coffee_teapot', 'Кофеварка/чайник'), ('cable_satellite_tv', 'Кабельное / спутниковое телевидение'), ('bidet', 'Биде'), ('connecting_rooms_available', 'Доступны смежные номера'), ('room_service', 'Обслуживание номеров'), ('safe', 'Безопасный'), ('sitting_area', 'Зона отдыха'), ('telephone', 'Телефон'), ('bottled_water', 'Бутилированная вода'), ('Safe', 'Сейф'), ('laptop_safe_box', 'Сейф для ноутбука'), ('private_bathroom', 'Частные ванные комнаты'), ('wake_up_service', 'Услуга будильник / будильник'), ('minibar', 'Минибар'), ('bath_or_shower', 'Ванна/душ'), ('Dressers', 'Комоды'), ('Mini kitchen', 'Мини кухня'), ('Fireplace', 'Камин'), ('Appetizers', 'Закуски'), ('2 rooms', '2 комнаты'), ('Nightstand', 'Тумба'), ('Television', 'Телевизор'), ('Bathroom', 'Ванная комната'), ('Phone', 'Телефон'), ('Chest of drawers', 'Комоды'), ('Slippers', 'Тапочки'), ('Bathrobe', 'Халат')], max_length=700, verbose_name='Удобства номера'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(default=1, upload_to='images/rooms/', verbose_name='Изображение номера'),
            preserve_default=False,
        ),
    ]
