# Generated by Django 4.2.3 on 2023-08-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_housing_check_in_time_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='without_credit_card',
        ),
        migrations.AddField(
            model_name='housing',
            name='without_card',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=True, verbose_name='Без банковской карты'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='free_cancellation',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Бесплатная отмена'),
        ),
    ]
