# Generated by Django 4.2.3 on 2023-08-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_remove_housingimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='image',
        ),
    ]
