# Generated by Django 4.2.3 on 2023-08-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_remove_roomimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='room',
        ),
        migrations.AddField(
            model_name='housing',
            name='image',
            field=models.ImageField(default=1, upload_to='images/housing', verbose_name='Изображение места жительства'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(default=1, upload_to='images/rooms', verbose_name='Изображение номера'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HousingImage',
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
