# Generated by Django 4.2.3 on 2023-09-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_initial'),
        ('travel', '0011_alter_housingreservation_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='is_favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='housing_set', to='favorite.housefavorite'),
        ),
    ]
