# Generated by Django 4.2.3 on 2023-08-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_alter_housing_check_in_time_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingreservation',
            options={'verbose_name': 'Бронь жилища', 'verbose_name_plural': 'Бронь жилищ'},
        ),
    ]
