# Generated by Django 4.2.3 on 2023-09-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_housingreservation_check_in_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingreservation',
            name='teens',
        ),
    ]
