# Generated by Django 4.2.3 on 2023-08-04 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_rating_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housereservation',
            options={'verbose_name': 'Бронь жилья', 'verbose_name_plural': 'Бронь жилищ'},
        ),
    ]
