# Generated by Django 4.2.3 on 2023-08-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_housing_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='breakfast_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость завтрака в US$ (с человека за ночь)'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='parking_location',
            field=models.CharField(choices=[('On-site', 'На территории'), ('Off-site', 'За территорией')], default=1, max_length=50, verbose_name='Местонахождение парковки'),
            preserve_default=False,
        ),
    ]
