# Generated by Django 4.2.3 on 2023-09-11 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_housing_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='is_favorite',
        ),
    ]
