# Generated by Django 4.2.3 on 2023-08-05 08:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_rename_cancellation_policy_housing_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housereservation',
            name='check_in_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 8, 5))], verbose_name='Заезд'),
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='check_out_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 8, 5))], verbose_name='Выезд'),
        ),
        migrations.AlterField(
            model_name='housereservation',
            name='destination',
            field=models.CharField(choices=[('Bishkek', 'Бишкек'), ('Jalal-Abad', 'Джалал-Абад'), ('Issyk-Kul', 'Иссык-Куль'), ('Osh', 'Ош'), ('Naryn', 'Нарын'), ('Talas', 'Талас'), ('Batken', 'Баткен')], max_length=100, verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='housing',
            name='region',
            field=models.CharField(choices=[('Bishkek', 'Бишкек'), ('Jalal-Abad', 'Джалал-Абад'), ('Issyk-Kul', 'Иссык-Куль'), ('Osh', 'Ош'), ('Naryn', 'Нарын'), ('Talas', 'Талас'), ('Batken', 'Баткен')], max_length=50, verbose_name='Область'),
        ),
    ]
