# Generated by Django 4.2.3 on 2023-08-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_alter_housereservation_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='image',
            field=models.ImageField(default=1, upload_to='images/housing/', verbose_name='Изображение места жительства'),
            preserve_default=False,
        ),
    ]
