# Generated by Django 4.2.3 on 2023-08-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_housing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='image',
        ),
    ]
