# Generated by Django 4.2.3 on 2023-08-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_alter_housingreservation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housingimage',
            options={'verbose_name': 'Изображение места жительства', 'verbose_name_plural': 'Изображения места жительств'},
        ),
        migrations.AlterModelOptions(
            name='roomimage',
            options={'verbose_name': 'Изображение номера', 'verbose_name_plural': 'Изображения номеров'},
        ),
    ]
