# Generated by Django 4.2.3 on 2023-09-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_alter_housingreview_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housingreview',
            old_name='user',
            new_name='gost',
        ),
    ]
