# Generated by Django 4.2.3 on 2023-08-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_remove_housing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/housing/', verbose_name='Изображение места жительства'),
        ),
    ]
