# Generated by Django 4.2.3 on 2023-08-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_alter_housingimage_options_alter_roomimage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='double_bed_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='king_bed_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='queen_bed_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='single_bed_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sofa_bed_count',
        ),
        migrations.AddField(
            model_name='room',
            name='double_bed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Двуспальных кроватей'),
        ),
        migrations.AddField(
            model_name='room',
            name='king_bed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Широких (king-size) кроватей'),
        ),
        migrations.AddField(
            model_name='room',
            name='queen_bed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Широких (queen-size) кроватей'),
        ),
        migrations.AddField(
            model_name='room',
            name='single_bed',
            field=models.PositiveIntegerField(default=1, verbose_name='Односпальных кроватей'),
        ),
        migrations.AddField(
            model_name='room',
            name='sofa_bed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Диван-кроватей'),
        ),
    ]
