# Generated by Django 4.2.3 on 2023-08-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_alter_housingimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/car/', verbose_name='Изображение'),
        ),
    ]
