# Generated by Django 4.2.3 on 2023-09-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_rename_user_housingreview_gost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housingreview',
            old_name='gost',
            new_name='user',
        ),
    ]
