# Generated by Django 4.2.3 on 2023-08-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_room_remove_housing_bed_type_remove_housing_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='images/rooms/', verbose_name='Изображение номера'),
        ),
    ]
