# Generated by Django 4.2.3 on 2023-08-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_alter_housing_accommodation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='policy',
            field=models.CharField(choices=[('До 00:00 в день заезда', 'До 00:00 в день заезда'), ('В любое время', 'В любое время')], max_length=50, verbose_name='Правила бесплатной отмены'),
        ),
    ]
