# Generated by Django 4.2.3 on 2023-08-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_remove_housereservation_user_remove_rating_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomimage',
            old_name='housing',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/rooms/', verbose_name='Изображение номера'),
        ),
    ]
