# Generated by Django 4.2.3 on 2023-08-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='bed_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='room',
            name='double_bed_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='free_cancellation',
        ),
        migrations.RemoveField(
            model_name='room',
            name='king_bed_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='max_guest_capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='num_rooms',
        ),
        migrations.RemoveField(
            model_name='room',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='room',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_per_night',
        ),
        migrations.RemoveField(
            model_name='room',
            name='queen_bed_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_amenities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_area',
        ),
        migrations.RemoveField(
            model_name='room',
            name='single_bed_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='smoking_allowed',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sofa_bed_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='without_card',
        ),
    ]
