# Generated by Django 4.2.3 on 2023-08-05 21:11

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_remove_room_bed_type_remove_room_bedrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('Single', 'Отдельные'), ('Double', 'Двуспальная'), ('Kingsize', 'Kingsize'), ('Queensize', 'Queensize'), ('Диван-кровать', 'Диван-кровать')], default=1, max_length=50, verbose_name='Тип кроватей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='bedrooms',
            field=models.CharField(choices=[('1 bedroom', '1 спальня'), ('2 bedrooms', '2 спальни'), ('More than 3 bedrooms', 'Больше 3 спален')], default=1, max_length=50, verbose_name='Количество спален'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='double_bed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество двуспальных кроватей'),
        ),
        migrations.AddField(
            model_name='room',
            name='free_cancellation',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Бесплатная отмена'),
        ),
        migrations.AddField(
            model_name='room',
            name='king_bed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество широких (king-size) кроватей'),
        ),
        migrations.AddField(
            model_name='room',
            name='max_guest_capacity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Максимальная вместимость гостей в номере'),
        ),
        migrations.AddField(
            model_name='room',
            name='num_rooms',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Количество комнат в номере'),
        ),
        migrations.AddField(
            model_name='room',
            name='payment',
            field=models.CharField(choices=[('Pay now', 'К оплате сейчас'), ('Prepayment', 'Предоплата'), ('Cash payment', 'Оплата наличными')], default='К оплате сейчас', max_length=50, verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='room',
            name='policy',
            field=models.CharField(choices=[('before_00_00_on_check_in_day', 'До 00:00 в день заезда'), ('anytime', 'В любое время')], default=1, max_length=50, verbose_name='Правила бесплатной отмены'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='цена за ночь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='queen_bed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество широких (queen-size) кроватей'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('air_conditioner', 'Кондиционер'), ('hair_dryer', 'Фен'), ('washing_machine', 'Стиральная машина'), ('iron', 'Утюг'), ('dryer', 'Сушильная машина'), ('fridge', 'Холодильник'), ('tv', 'Телевизор'), ('microwave', 'Микроволновка'), ('heating', 'Отопление'), ('sofa_bed', 'Диван-кровать'), ('folding_bed', 'Раскладная кровать'), ('Double bed', 'Двуспальная кровать'), ('wardrobe', 'Шкаф или гардероб'), ('linen', 'Белье'), ('clothes_hanger', 'Вешалка для одежды'), ('complimentary_toiletries', 'Бесплатные туалетно-косметические принадлежности'), ('toilet_paper', 'Туалетная бумага'), ('kitchen_utensils', 'Кухонные принадлежности'), ('electric_kettle', 'Электрический чайник'), ('city_view', 'Вид на город'), ('garden_view', 'Вид на сад'), ('high_toilet', 'Высокий туалет'), ('toilet_with_handles', 'Туалет с поручнями'), ('accessible_to_disabled_guests', 'Подходит для гостей с ограниченными возможностями'), ('work_desk', 'Рабочий стол'), ('room_cleaning', 'Уборка'), ('coffee_teapot', 'Кофеварка/чайник'), ('cable_satellite_tv', 'Кабельное / спутниковое телевидение'), ('bidet', 'Биде'), ('connecting_rooms_available', 'Доступны смежные номера'), ('room_service', 'Обслуживание номеров'), ('safe', 'Безопасный'), ('sitting_area', 'Зона отдыха'), ('telephone', 'Телефон'), ('bottled_water', 'Бутилированная вода'), ('Safe', 'Сейф'), ('laptop_safe_box', 'Сейф для ноутбука'), ('private_bathroom', 'Частные ванные комнаты'), ('wake_up_service', 'Услуга будильник / будильник'), ('minibar', 'Минибар'), ('flat_screen_tv', 'Телевизор с плоским экраном'), ('bath_or_shower', 'Ванна/душ'), ('Dressers', 'Комоды'), ('Mini kitchen', 'Мини кухня'), ('Fireplace', 'Камин'), ('Appetizers', 'Закуски'), ('2 rooms', '2 комнаты')], default=1, max_length=100, verbose_name='Удобства номера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_area',
            field=models.PositiveIntegerField(default=1, verbose_name='Площадь комнаты(м²)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='single_bed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество односпальных кроватей'),
        ),
        migrations.AddField(
            model_name='room',
            name='smoking_allowed',
            field=models.BooleanField(default=False, verbose_name='Разрешено ли курение в комнате'),
        ),
        migrations.AddField(
            model_name='room',
            name='sofa_bed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество диван-кроватей'),
        ),
        migrations.AddField(
            model_name='room',
            name='without_card',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=True, verbose_name='Без банковской карты'),
        ),
    ]
